# Expose your documentation as raw JSON (Swagger/OpenAPI compliant)
app.swagger_json:
    path: /bilemob2bapi/doc.json
    methods: ['GET']
    defaults: { _controller: nelmio_api_doc.controller.swagger }

## Requires the Asset component and the Twig bundle
## $ composer require twig asset
# Expose the interactive graphical Swagger UI interface
app.swagger_ui:
    path: /bilemob2bapi/doc
    methods: ['GET']
    defaults: { _controller: nelmio_api_doc.controller.swagger_ui }
