<?php

// src/Serializer/PaginatedCollectionNormalizer.php

namespace App\Serializer;

use Symfony\Component\HttpFoundation\RequestStack;
use Symfony\Component\Routing\Generator\UrlGeneratorInterface;
use Symfony\Component\Serializer\Normalizer\NormalizerInterface;

class PaginatedCollectionNormalizer implements NormalizerInterface
{
    /**
     * This normalizer processes pre-constructed array structures generated by the controller layer.
     */
    public function __construct(
        private readonly UrlGeneratorInterface $router,
        private readonly RequestStack $requestStack
    ) {
    }

    /**
     * @param mixed $object
     * @param string|null $format
     * @param array<string, mixed> $context
     * @return array<string, mixed>|string|int|float|bool|\ArrayObject<string, mixed>|null
     */
    public function normalize(mixed $object, ?string $format = null, array $context = []): array|string|int|float|bool|\ArrayObject|null
    {
        // 1. Isolate the incoming metadata layout configuration to safely append nested links
        $meta = $object['meta'];

        // 2. Inject nested hypermedia controls for the Client object inside the meta context envelope if present
        if (isset($meta['client']) && is_array($meta['client'])) {
            $meta['client']['_links'] = [
                'self' => [
                    'href' => $this->router->generate('app_client_profile', [], UrlGeneratorInterface::ABSOLUTE_URL)
                ]
            ];
        }

        // 3. Map the structural array envelope layout to keep everything structured properly
        $normalizedData = [
            'meta' => $meta,
            'data' => $object['data'] // Contains already recursively normalized items
        ];

        // 4. Retrieve the current request context to compute target routing dynamically
        $request = $this->requestStack->getCurrentRequest();
        if (!$request) {
            /** @var array<string, mixed>|string|int|float|bool|\ArrayObject<string, mixed>|null $normalizedData */
            return $normalizedData;
        }

        $route = (string)$request->attributes->get('_route');

        // Preserve any existing query parameters (e.g., search or custom filters) except active page/limit bounds
        $queryParams = $request->query->all();

        // Extract pagination parameters safely from the updated 'meta' configuration array
        $currentPage = (int) $meta['current_page'];
        $totalPages = (int) $meta['total_pages'];
        $limit = (int) $meta['limit'];

        // 5. Build absolute root-level HATEOAS pagination links matching Richardson Maturity Level 3
        $normalizedData['_links'] = [
            'first' => [
                'href' => $this->router->generate($route, array_merge($queryParams, ['page' => 1, 'limit' => $limit]), UrlGeneratorInterface::ABSOLUTE_URL)
            ],
            'next' => $currentPage < $totalPages ? [
                'href' => $this->router->generate($route, array_merge($queryParams, ['page' => $currentPage + 1, 'limit' => $limit]), UrlGeneratorInterface::ABSOLUTE_URL)
            ] : null,
            'prev' => $currentPage > 1 ? [
                'href' => $this->router->generate($route, array_merge($queryParams, ['page' => $currentPage - 1, 'limit' => $limit]), UrlGeneratorInterface::ABSOLUTE_URL)
            ] : null,
            'last' => [
                'href' => $this->router->generate($route, array_merge($queryParams, ['page' => $totalPages, 'limit' => $limit]), UrlGeneratorInterface::ABSOLUTE_URL)
            ],
        ];

        /** @var array<string, mixed> $normalizedData */
        return $normalizedData;
    }

    /**
     * Checks whether the incoming data structure qualifies for collection-level hypermedia enrichment.
     */
    public function supportsNormalization(mixed $data, ?string $format = null, array $context = []): bool
    {
        // Explicitly intercept array envelopes containing valid pagination metadata structures
        return is_array($data) && isset($data['meta']) && isset($data['data']);
    }

    /**
     * Optimizes normalizer caching routines within the Symfony Dependency Injection component.
     */
    public function getSupportedTypes(?string $format): array
    {
        return [
            'array' => true, // Tells Symfony that this normalizer is caching-optimized specifically for native arrays
        ];
    }
}
