spring.application.name=MedQuery
spring.datasource.url=jdbc:mysql://localhost:3306/medquery
spring.datasource.username=medquery_user
spring.datasource.password=medquery_pass

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.flyway.enabled=true

server.error.include-stacktrace=never

api.security.token.secret=${JWT_SECRET:12345678}