"""BrainPack — P2.1 Brain Pack Prototype (owner: claude-code).

Status: EXPERIMENTAL, NOT wired into MemoryController.search() or any runtime
path. Compiles a "brain" for ONE task, with a fixed budget.

What it delivers: a single artifact (Markdown + JSON sidecar) handed to an
agent alongside its task. It contains exactly the relevant subgraph, not the
whole vault.

Pipeline:
    task -> hybrid retrieval (seeds) -> synapse-weighted spreading activation
         -> budget-constrained selection -> sectioning by cognitive role
         -> OBSERVED memory trace (what actually went in, generated by code,
            never by the model)

IMPORTANT — this is a compiled-context artifact, NOT a retrieval ranking
benchmark. It does not produce Recall@K/MRR and must never be cited as such;
for ranking evidence see cognitive_core/benchmarks/retrieval_ab.py, which is
itself explicitly NOT proof of P1.1 production readiness. What this module
reports instead: relevant-memory coverage, token budget, selected node count,
direct-vs-graph node origin, warnings, and trace reproducibility.

Explicit contract, restated in every emitted trace and in the Markdown header:
    observed retrieval != proven causal influence
The pack records what was RETRIEVED. It does not and cannot claim the model's
answer was actually caused by any specific item in it.

CLI:
    python -m cognitive_core.brain_pack --task "..." --budget 8000 --out pack.md
"""
from __future__ import annotations

import argparse
import hashlib
import json
import sys
from dataclasses import dataclass, field
from datetime import datetime, timezone
from pathlib import Path
from typing import Dict, List, Optional, Sequence, Tuple

from .hybrid_retrieval import HybridRetriever, OllamaEmbedder
from .synapse_store import SynapseStore
from .vault_index import Note, VaultIndex

# Percentage budget per cognitive role. Procedures and contradictions are
# prioritized: an agent that violates a known procedure produces the most
# expensive kind of failure.
SECTION_QUOTA = {
    "rules": 0.15,
    "procedures": 0.25,
    "facts": 0.30,
    "lessons": 0.20,
    "contradictions": 0.10,
}
TYPE_TO_SECTION = {
    "procedure": "procedures", "protocol": "procedures", "rules": "procedures",
    "lesson": "lessons", "error": "lessons", "experience": "lessons",
    "decision": "facts", "knowledge": "facts", "fact": "facts",
    "project": "facts", "resource": "facts", "core": "rules", "governance": "rules",
}
CHARS_PER_TOKEN = 4  # conservative estimate; swap for a real tokenizer if available

OBSERVED_NOT_CAUSAL = "observed retrieval != proven causal influence"


def _ensure_utf8_stdout() -> None:
    """See 30_SCRIPTS/knowledge/edge_proposer.py::_ensure_utf8_stdout."""
    for stream in (sys.stdout, sys.stderr):
        try:
            stream.reconfigure(encoding="utf-8", errors="replace")
        except (AttributeError, ValueError):
            pass


def est_tokens(text: str) -> int:
    return max(1, len(text) // CHARS_PER_TOKEN)


@dataclass
class PackedNote:
    note: Note
    section: str
    activation: float
    origin: str          # "seed" | "hop"
    tokens: int
    excerpt: str


@dataclass
class ExcludedNote:
    note_id: str
    section: str
    activation: float
    reason: str           # "section_quota" | "total_budget"


@dataclass
class BrainPack:
    task: str
    generated: str
    budget_tokens: int
    used_tokens: int
    items: List[PackedNote] = field(default_factory=list)
    excluded: List[ExcludedNote] = field(default_factory=list)
    observed_edges: List[Tuple[str, str]] = field(default_factory=list)
    warnings: List[str] = field(default_factory=list)
    dense_active: bool = False

    @property
    def pack_id(self) -> str:
        h = hashlib.sha256(
            (self.task + self.generated + str(len(self.items))).encode()
        ).hexdigest()[:12]
        return f"bp_{h}"

    def coverage_metrics(self) -> Dict[str, object]:
        """Metrics this module actually claims: NOT Recall@K/MRR."""
        direct = sum(1 for i in self.items if i.origin == "seed")
        graph = sum(1 for i in self.items if i.origin == "hop")
        return {
            "selected_node_count": len(self.items),
            "direct_selected_nodes": direct,
            "graph_selected_nodes": graph,
            "excluded_due_to_budget": len(self.excluded),
            "token_budget": self.budget_tokens,
            "tokens_used": self.used_tokens,
            "token_efficiency": round(self.used_tokens / max(self.budget_tokens, 1), 4),
            "dense_provider_active": self.dense_active,
        }

    def observed_trace(self) -> Dict:
        """OBSERVED trace: produced by deterministic code, BEFORE the model
        sees anything. Never accepts model self-report."""
        return {
            "pack_id": self.pack_id,
            "task_sha256": hashlib.sha256(self.task.encode()).hexdigest(),
            "generated": self.generated,
            "budget_tokens": self.budget_tokens,
            "used_tokens": self.used_tokens,
            "memory_ids": [i.note.id for i in self.items],
            "memory_paths": [i.note.path.as_posix() for i in self.items],
            "memory_lifecycle": {i.note.id: i.note.lifecycle for i in self.items},
            "memory_verification": {i.note.id: i.note.verification for i in self.items},
            "seed_ids": [i.note.id for i in self.items if i.origin == "seed"],
            "hop_ids": [i.note.id for i in self.items if i.origin == "hop"],
            "observed_edges": [list(e) for e in self.observed_edges],
            "excluded_due_to_budget": [
                {"id": e.note_id, "section": e.section, "reason": e.reason}
                for e in self.excluded
            ],
            "dense_provider_active": self.dense_active,
            "warnings": self.warnings,
            "contract": OBSERVED_NOT_CAUSAL,
        }

    def to_markdown(self) -> str:
        lines = [
            f"# BRAIN PACK — {self.pack_id}",
            "",
            f"> Task: {self.task}",
            f"> Generated: {self.generated} :: budget {self.budget_tokens} tok :: "
            f"used {self.used_tokens} tok :: {len(self.items)} nodes",
            "",
            "**Contract:** this is the context retrieved for this task. If a "
            "needed fact is not here, say explicitly that memory does not "
            "contain it — do not invent it. Notes marked `UNVERIFIED` are "
            f"hypotheses, not truth. {OBSERVED_NOT_CAUSAL}.",
            "",
        ]
        for section in ("rules", "procedures", "facts", "lessons", "contradictions"):
            items = [i for i in self.items if i.section == section]
            if not items:
                continue
            lines += [f"## {section.upper()}", ""]
            for it in sorted(items, key=lambda x: (-x.activation, x.note.id)):
                flags = []
                if it.note.verification != "verified":
                    flags.append(it.note.verification.upper())
                if it.note.lifecycle != "ACTIVE":
                    flags.append(it.note.lifecycle)
                if it.origin == "hop":
                    flags.append("VIA-GRAPH")
                tag = f" `[{' :: '.join(flags)}]`" if flags else ""
                lines += [
                    f"### {it.note.title}{tag}",
                    f"<!-- id:{it.note.id} act:{it.activation:.3f} src:{it.note.path.as_posix()} -->",
                    it.excerpt,
                    "",
                ]
        if self.warnings:
            lines += ["## MEMORY WARNINGS", ""] + [f"- {w}" for w in self.warnings] + [""]
        return "\n".join(lines)


class BrainPackCompiler:
    def __init__(self, index: VaultIndex, synapses: SynapseStore,
                 retriever: Optional[HybridRetriever] = None):
        self.index = index
        self.synapses = synapses
        self.retriever = retriever or HybridRetriever(index)

    @staticmethod
    def _section_for(note: Note) -> str:
        return TYPE_TO_SECTION.get(note.type, TYPE_TO_SECTION.get(note.category, "facts"))

    @staticmethod
    def _excerpt(note: Note, max_tokens: int) -> str:
        limit = max_tokens * CHARS_PER_TOKEN
        body = note.body.strip()
        if len(body) <= limit:
            return body
        cut = body[:limit]
        tail = cut.rfind("\n")
        return (cut[:tail] if tail > limit * 0.5 else cut).rstrip() + "\n...[truncated]"

    def compile(self, task: str, budget_tokens: int = 8000, seed_k: int = 8,
                max_hops: int = 2, max_note_tokens: int = 500,
                lifecycles: Sequence[str] = ("ACTIVE", "VERIFIED")) -> BrainPack:
        pack = BrainPack(
            task=task,
            generated=datetime.now(timezone.utc).isoformat(timespec="seconds"),
            budget_tokens=budget_tokens,
            used_tokens=0,
            dense_active=getattr(self.retriever, "dense_active", False),
        )

        hits = self.retriever.search(task, top_k=seed_k, lifecycles=lifecycles)
        if not hits:
            hits = self.retriever.search(task, top_k=seed_k)
            if hits:
                pack.warnings.append(
                    "No ACTIVE/VERIFIED result; falling back to REVIEW material "
                    "(treat it as a hypothesis, not canonical truth)."
                )
        if not hits:
            pack.warnings.append("Memory contains nothing relevant to this task.")
            return pack

        seeds = {h.note.id: h.score for h in hits}
        max_seed = max(seeds.values()) or 1.0
        seeds = {k: v / max_seed for k, v in seeds.items()}

        activation = self.synapses.spread(seeds, max_hops=max_hops, record=True)
        for src in list(seeds):
            for syn in self.synapses.neighbors(src):
                if syn.target_id in activation:
                    pack.observed_edges.append((syn.source_id, syn.target_id))

        candidates = []
        for note_id, score in activation.items():
            note = self.index.by_id.get(note_id)
            if note is None:
                continue
            candidates.append((note, score, "seed" if note_id in seeds else "hop"))
        # Deterministic tie-break: activation score desc, then note id asc, so
        # a rerun on identical seeds/graph always yields identical selection.
        candidates.sort(key=lambda c: (-c[1], c[0].id))

        quotas = {s: int(budget_tokens * q) for s, q in SECTION_QUOTA.items()}
        used_per_section: Dict[str, int] = {s: 0 for s in quotas}
        total = 0

        for note, score, origin in candidates:
            section = self._section_for(note)
            if note.type == "contradiction" or "contradicts" in note.tags:
                section = "contradictions"
            excerpt = self._excerpt(note, max_note_tokens)
            tokens = est_tokens(excerpt) + est_tokens(note.title) + 20
            if used_per_section.get(section, 0) + tokens > quotas.get(section, 0):
                pack.excluded.append(ExcludedNote(note.id, section, round(score, 4), "section_quota"))
                continue
            if total + tokens > budget_tokens:
                pack.excluded.append(ExcludedNote(note.id, section, round(score, 4), "total_budget"))
                continue
            used_per_section[section] = used_per_section.get(section, 0) + tokens
            total += tokens
            pack.items.append(PackedNote(note, section, round(score, 4), origin, tokens, excerpt))

        pack.used_tokens = total
        assert pack.used_tokens <= pack.budget_tokens, "budget contract violated"
        if not any(i.section == "procedures" for i in pack.items):
            pack.warnings.append("No procedure retrieved -- the task may need one that isn't written yet.")
        unverified = sum(1 for i in pack.items if i.note.verification != "verified")
        if pack.items and unverified / len(pack.items) > 0.5:
            pack.warnings.append(
                f"{unverified}/{len(pack.items)} nodes are unverified. Low pack reliability."
            )
        return pack


def main(argv: Optional[Sequence[str]] = None) -> int:
    _ensure_utf8_stdout()
    ap = argparse.ArgumentParser(description="Compiles a Brain Pack for one task.")
    ap.add_argument("--task", required=True)
    ap.add_argument("--vault", default=".")
    ap.add_argument("--budget", type=int, default=8000)
    ap.add_argument("--seeds", type=int, default=8)
    ap.add_argument("--hops", type=int, default=2)
    ap.add_argument("--synapses", default="05_DATA/synapses.json")
    ap.add_argument("--out", default="50_ARTIFACTS/brain_pack.md")
    ap.add_argument("--trace-dir", default="08_OBSERVABILITY/brain_pack_traces")
    ap.add_argument("--embed", action="store_true", help="Use local Ollama embeddings")
    ap.add_argument("--lifecycle", default="ACTIVE,VERIFIED")
    args = ap.parse_args(argv)

    vault = Path(args.vault)
    index = VaultIndex.load(vault)
    syn_path = vault / args.synapses
    synapses = SynapseStore.load(syn_path)
    if not synapses.all():
        synapses = SynapseStore.from_index(index)

    embedder = OllamaEmbedder() if args.embed else None
    retriever = HybridRetriever(index, embedder=embedder)
    dense_ok = True
    if embedder and not retriever.build_dense_index():
        dense_ok = False
        print("[warn] DENSE_PROVIDER=UNAVAILABLE -- continuing with BM25 + entity only")

    compiler = BrainPackCompiler(index, synapses, retriever)
    pack = compiler.compile(
        args.task, budget_tokens=args.budget, seed_k=args.seeds,
        max_hops=args.hops, lifecycles=tuple(args.lifecycle.split(",")),
    )
    if args.embed and not dense_ok:
        pack.warnings.append("DENSE_PROVIDER=UNAVAILABLE: --embed was requested but Ollama "
                              "did not respond; this pack used BM25+entity only, not dense.")

    out = vault / args.out
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(pack.to_markdown(), encoding="utf-8")

    trace_dir = vault / args.trace_dir
    trace_dir.mkdir(parents=True, exist_ok=True)
    (trace_dir / f"{pack.pack_id}.json").write_text(
        json.dumps(pack.observed_trace(), indent=2, ensure_ascii=False), encoding="utf-8"
    )
    synapses.save(syn_path)

    print(f"{pack.pack_id}: {len(pack.items)} nodes :: {pack.used_tokens}/{pack.budget_tokens} tok -> {out}")
    print("coverage:", json.dumps(pack.coverage_metrics()))
    for w in pack.warnings:
        print(f"  [warn] {w}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
