from typing import List, Dict, Any, Optional
from .motivation import UtilityTracker

class AttentionModel:
    """
    Computes attention scores for nodes in Working Memory.
    Attention determines which notes stay in the bounded Working Memory
    when new nodes are introduced.
    Integrates ACT-R utility tracker feedback.
    """
    def __init__(self, activation_weight: float = 0.45, confidence_weight: float = 0.25, recency_weight: float = 0.2, utility_weight: float = 0.1):
        self.activation_weight = activation_weight
        self.confidence_weight = confidence_weight
        self.recency_weight = recency_weight
        self.utility_weight = utility_weight
        self.utility_tracker = UtilityTracker.get_instance()
        
        self.confidence_scores = {
            "very_high": 1.0,
            "high": 0.8,
            "medium": 0.5,
            "low": 0.2,
            "unknown": 0.1
        }
        
    def calculate_score(self, node: Dict[str, Any], activation: float, recency_tick: int, current_tick: int, action_type: Optional[str] = None) -> float:
        """
        Calculate an attention score bounded between 0.0 and 1.0.
        Recency decays as current_tick increases relative to recency_tick.
        Utility bonus boosts notes generated by high-utility action types.
        """
        conf_val = node.get("confidence", "unknown")
        conf_score = self.confidence_scores.get(conf_val, 0.1)
        
        age = current_tick - recency_tick
        recency_score = max(0.0, 1.0 - (age * 0.05))
        
        act_type = action_type or node.get("category", node.get("type", "default"))
        utility_score = self.utility_tracker.get_utility(act_type)
        
        total_score = (
            (activation * self.activation_weight) +
            (conf_score * self.confidence_weight) +
            (recency_score * self.recency_weight) +
            (utility_score * self.utility_weight)
        )
        
        return min(1.0, max(0.0, total_score))
