using System.Text;
using EventLogAnalyzer.Core.Models;

namespace EventLogAnalyzer.Core.Remediation;

/// <summary>
/// Turns an Issue into a human-readable PowerShell script. This class has
/// NO reference to System.Diagnostics.Process and never writes to disk or
/// executes anything - it only returns a string. Execution (if ever) is a
/// deliberate, separately-confirmed action in the App layer.
/// </summary>
public sealed class RemediationScriptBuilder
{
    public string Build(Issue issue)
    {
        var sb = new StringBuilder();
        sb.AppendLine("# ============================================================");
        sb.AppendLine($"# Suggested remediation for: {issue.Title}");
        sb.AppendLine($"# Category: {issue.Category}  |  Impact: {issue.Impact}  |  Events: {issue.Count}");
        sb.AppendLine("# Generated by EventLog Analyzer. REVIEW BEFORE RUNNING.");
        sb.AppendLine("# Nothing in this application executes this script automatically.");
        sb.AppendLine("# ============================================================");
        sb.AppendLine();

        switch (issue.Category)
        {
            case "RepeatedServiceCrash":
                AppendServiceCrashScript(sb, issue);
                break;
            case "DiskError":
                AppendDiskErrorScript(sb);
                break;
            case "FailedLogonStorm":
                sb.AppendLine("# No automated remediation is offered for failed-logon bursts -");
                sb.AppendLine("# this requires human judgement (identify source, confirm intent).");
                sb.AppendLine("Write-Host 'Review Security log 4625 events manually; see recommendation panel.'");
                break;
            default:
                sb.AppendLine("# No script template registered for this issue category yet.");
                sb.AppendLine("# See README section 'Adding a new remediation recipe'.");
                break;
        }

        return sb.ToString();
    }

    private static void AppendServiceCrashScript(StringBuilder sb, Issue issue)
    {
        var serviceName = ExtractServiceNameFromTitle(issue.Title);
        sb.AppendLine($"$service = '{serviceName}'");
        sb.AppendLine();
        sb.AppendLine("# 1. Confirm current configuration (read-only)");
        sb.AppendLine("sc.exe qc $service");
        sb.AppendLine();
        sb.AppendLine("# 2. Inspect recovery actions currently configured");
        sb.AppendLine("sc.exe qfailure $service");
        sb.AppendLine();
        sb.AppendLine("# 3. OPTIONAL: set a sane recovery policy (restart after 60s, up to 3 times,");
        sb.AppendLine("#    reset failure count after 1 day). Uncomment only after confirming intent:");
        sb.AppendLine("# sc.exe failure $service reset= 86400 actions= restart/60000/restart/60000/restart/60000");
        sb.AppendLine();
        sb.AppendLine("# 4. Pull recent errors from the service's own event source for root cause");
        sb.AppendLine("Get-WinEvent -LogName Application -MaxEvents 50 |");
        sb.AppendLine("  Where-Object { $_.ProviderName -like \"*$service*\" } |");
        sb.AppendLine("  Select-Object TimeCreated, Id, LevelDisplayName, Message |");
        sb.AppendLine("  Format-Table -AutoSize");
    }

    private static void AppendDiskErrorScript(StringBuilder sb)
    {
        sb.AppendLine("# 1. Read-only filesystem scan (no repair without a second, explicit run)");
        sb.AppendLine("chkdsk C: /scan");
        sb.AppendLine();
        sb.AppendLine("# 2. Check S.M.A.R.T. predictive-failure status");
        sb.AppendLine("Get-PhysicalDisk | Select-Object DeviceId, FriendlyName, HealthStatus, OperationalStatus");
        sb.AppendLine();
        sb.AppendLine("# 3. If HealthStatus is not 'Healthy', schedule hardware replacement before");
        sb.AppendLine("#    considering an offline repair pass ('chkdsk C: /f' requires a reboot).");
    }

    private static string ExtractServiceNameFromTitle(string title)
    {
        // Title format from RepeatedServiceCrashDetector: "'<name>' service is crash-looping"
        var start = title.IndexOf('\'');
        var end = title.IndexOf('\'', start + 1);
        return start >= 0 && end > start ? title[(start + 1)..end] : "UNKNOWN_SERVICE";
    }
}
