"""
Domain models defined using Pydantic V2 with strict type hinting.
Zero-trust data flow invariants across application layers.
"""

from datetime import datetime, timezone
from enum import Enum
from typing import Any
from pydantic import BaseModel, Field, ConfigDict, field_validator


class SignalType(str, Enum):
    """Trading signal action type."""
    BUY = "BUY"
    SELL = "SELL"
    HOLD = "HOLD"
    CLOSE = "CLOSE"


class TimeFrame(str, Enum):
    """Supported MetaTrader 5 timeframes."""
    M1 = "M1"
    M5 = "M5"
    M15 = "M15"
    M30 = "M30"
    H1 = "H1"
    H4 = "H4"
    D1 = "D1"


class TickData(BaseModel):
    """Market tick entity."""
    model_config = ConfigDict(frozen=True, extra="forbid")

    symbol: str = Field(..., min_length=1, description="Financial asset symbol (e.g. XAUUSD)")
    bid: float = Field(..., gt=0.0, description="Bid price")
    ask: float = Field(..., gt=0.0, description="Ask price")
    last: float = Field(default=0.0, ge=0.0, description="Last traded price")
    volume: float = Field(default=0.0, ge=0.0, description="Tick volume")
    timestamp: datetime = Field(default_factory=lambda: datetime.now(timezone.utc), description="Tick UTC timestamp")

    @field_validator("ask")
    @classmethod
    def validate_spread(cls, v: float, info: Any) -> float:
        if "bid" in info.data and v < info.data["bid"]:
            raise ValueError("Ask price cannot be strictly less than Bid price")
        return v


class BarData(BaseModel):
    """OHLCV Bar entity representing historical candle."""
    model_config = ConfigDict(frozen=True, extra="forbid")

    time: datetime = Field(..., description="Bar open time UTC")
    open: float = Field(..., gt=0.0)
    high: float = Field(..., gt=0.0)
    low: float = Field(..., gt=0.0)
    close: float = Field(..., gt=0.0)
    tick_volume: int = Field(default=0, ge=0)
    spread: int = Field(default=0, ge=0)
    real_volume: int = Field(default=0, ge=0)


class SignalObject(BaseModel):
    """Trading decision generated by strategy."""
    model_config = ConfigDict(frozen=True, extra="forbid")

    symbol: str = Field(..., min_length=1)
    signal_type: SignalType = Field(...)
    confidence: float = Field(default=1.0, ge=0.0, le=1.0, description="Confidence rating between 0 and 1")
    target_price: float = Field(default=0.0, ge=0.0)
    stop_loss: float = Field(default=0.0, ge=0.0)
    take_profit: float = Field(default=0.0, ge=0.0)
    volume: float = Field(default=0.0, ge=0.0, description="Requested lot size")
    metadata: dict[str, Any] = Field(default_factory=dict, description="Strategy diagnostic context")
    timestamp: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))


class Position(BaseModel):
    """Open trade position state."""
    model_config = ConfigDict(frozen=True, extra="forbid")

    ticket: int = Field(..., gt=0, description="Broker position ticket ID")
    symbol: str = Field(..., min_length=1)
    type: SignalType = Field(..., description="BUY or SELL position type")
    volume: float = Field(..., gt=0.0, description="Lot size")
    open_price: float = Field(..., gt=0.0)
    sl: float = Field(default=0.0, ge=0.0)
    tp: float = Field(default=0.0, ge=0.0)
    profit: float = Field(default=0.0, description="Floating PnL in account currency")
    timestamp: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))


class AccountInfo(BaseModel):
    """Broker account state snapshot."""
    model_config = ConfigDict(frozen=True, extra="forbid")

    login: int = Field(..., gt=0)
    trade_mode: int = Field(default=0, description="0=Demo, 1=Contest, 2=Real")
    leverage: int = Field(default=100, gt=0)
    balance: float = Field(..., ge=0.0)
    equity: float = Field(..., ge=0.0)
    margin: float = Field(default=0.0, ge=0.0)
    free_margin: float = Field(default=0.0, ge=0.0)
    profit: float = Field(default=0.0)
    currency: str = Field(default="USD")


class OrderResult(BaseModel):
    """Execution result returned by BrokerClient."""
    model_config = ConfigDict(frozen=True, extra="forbid")

    success: bool = Field(..., description="True if order was filled or accepted")
    retcode: int = Field(..., description="MT5 return code")
    deal: int = Field(default=0, ge=0, description="Deal ticket ID if executed")
    order: int = Field(default=0, ge=0, description="Order ticket ID")
    volume: float = Field(default=0.0, ge=0.0)
    price: float = Field(default=0.0, ge=0.0)
    bid: float = Field(default=0.0, ge=0.0)
    ask: float = Field(default=0.0, ge=0.0)
    comment: str = Field(default="")
    request_id: int = Field(default=0)
    error_message: str = Field(default="")
    timestamp: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))


class AuditEvent(BaseModel):
    """Tamper-evident audit event log entry chained with SHA-256."""
    model_config = ConfigDict(frozen=True, extra="forbid")

    event_id: str = Field(..., description="UUID or unique sequence identifier")
    timestamp: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))
    event_type: str = Field(..., min_length=1)
    payload: dict[str, Any] = Field(default_factory=dict)
    prev_hash: str = Field(..., description="SHA-256 hash of previous event")
    current_hash: str = Field(..., description="SHA-256 hash of current event content + prev_hash")
