<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Balsam.Identity.Application\Balsam.Identity.Application.csproj" />
    <ProjectReference Include="..\..\..\Balsam.SharedKernel\Balsam.SharedKernel.csproj" />
  </ItemGroup>

</Project>
