using LogAnalyzer.Dfir.Analysis;
using LogAnalyzer.Dfir.FileSystem;
using LogAnalyzer.Dfir.Integrity;
using LogAnalyzer.Dfir.IO;
using LogAnalyzer.Dfir.Model;
using LogAnalyzer.Dfir.Persistence;
using LogAnalyzer.Dfir.Windows.Parsers;
using Xunit;

namespace LogAnalyzer.Dfir.Tests.Synthetic;

/// <summary>
/// Parser regression tests over the synthetic corpus (owner decision 7). They run on every pull request, on Windows and Linux,
/// and need no real evidence. The release gate counts these tests (Category=SyntheticCorpus) as the "synthetic corpus" check.
/// </summary>
[Trait(SyntheticCorpus.TraitName, SyntheticCorpus.TraitValue)]
public sealed class SyntheticCorpusTests : IDisposable
{
    private readonly string _dir = Path.Combine(Path.GetTempPath(), "ladfir_synth_" + Guid.NewGuid().ToString("N"));

    public SyntheticCorpusTests() { Directory.CreateDirectory(_dir); SyntheticCorpus.Materialize(_dir); }
    public void Dispose() => Directory.Delete(_dir, true);

    private string P(string name) => Path.Combine(_dir, name.Replace('/', Path.DirectorySeparatorChar));
    private static EvidenceItem Item(string path, string type) => new() { EvidenceId = "EV-S", CaseId = "C-SYNTH", Source = type, SourceType = type, StoredPath = path };

    // ---- the corpus itself -----------------------------------------------------------------------------------------------------

    /// <summary>
    /// Pinned SHA-256 of every generated artifact. If a generator changes on purpose, update the value in the same commit and
    /// say why; if it changes by accident (a clock, an ordering, a platform difference), this is the test that notices.
    /// </summary>
    private static readonly Dictionary<string, string> Manifest = new()
    {
        ["prefetch/SETUP.EXE-0A1B2C3D.pf"] = "92F9879FBC2D19E884BF7C5226B1534E6BF47B5D76BF6D76B18C2A678C5BAE8C",
        ["lnk/SETUP.EXE.lnk"] = "AADCA7F966CCDB37EF53F1E8B67D1DDC17E965820D5087BF5A782EDFF99B0DD3",
        ["registry/NTUSER.DAT"] = "16307F8006B9AE9906636B2AEA86454D0925597F4AFBC1E782E693C32C890836",
        ["registry/SOFTWARE"] = "075C80DEB17E55E5B5100CA3046004E132387B5E770B0E7F529299EDC966BBC7",
        ["tasks/orchestratormaintain"] = "0ADD7BF4A9E950FB04F6648B24817E2EB0A173AE0BAD3F3C8AD4156BF92CCDF1",
        ["evtx/container.evtx"] = "72FA83445932E003D73507766F73AC0A39151CA466F4CEF04A669F44924E9FCC",
    };

    [Fact]
    public void Corpus_is_deterministic_and_matches_the_pinned_manifest()
    {
        var first = SyntheticCorpus.All();
        var second = SyntheticCorpus.All();
        Assert.Equal(Manifest.Keys.Order(), first.Keys.Order());
        var drift = new List<string>();
        foreach (var (name, bytes) in first)
        {
            Assert.Equal(SyntheticCorpus.Sha256(bytes), SyntheticCorpus.Sha256(second[name]));      // two runs, same bytes
            Assert.Equal(bytes, File.ReadAllBytes(P(name)));                                          // Materialize writes exactly them
            if (Manifest[name] != SyntheticCorpus.Sha256(bytes)) drift.Add($"{name} = {SyntheticCorpus.Sha256(bytes)}");
        }
        Assert.True(drift.Count == 0, "generated bytes differ from the pinned manifest:\n" + string.Join("\n", drift));
    }

    // ---- Prefetch ----------------------------------------------------------------------------------------------------------------

    [Fact]
    public void Prefetch_is_recognised_and_decoded()
    {
        var p = P("prefetch/SETUP.EXE-0A1B2C3D.pf");
        Assert.Equal("prefetch", EvidenceFingerprint.Detect(p));
        var pf = PrefetchParser.Read(p);
        Assert.Equal(30, pf.Version);
        Assert.Equal(SyntheticCorpus.PrefetchExe, pf.ExeName);
        Assert.Equal(SyntheticCorpus.PrefetchHash, pf.Hash);
        Assert.Equal(SyntheticCorpus.PrefetchRunCount, pf.RunCount);
        Assert.Equal([SyntheticCorpus.Run1, SyntheticCorpus.Run2, SyntheticCorpus.Run3], pf.RunTimesUtc.Select(t => t.UtcDateTime).ToArray());
        Assert.Equal(SyntheticCorpus.PrefetchFiles, pf.ReferencedFiles);
        Assert.EndsWith(@"\USERS\U\DOWNLOADS\TOOL_302044\SETUP.EXE", pf.ExePathGuess);
        Assert.Contains("1234ABCD", Assert.Single(pf.Volumes));
    }

    [Fact]
    public void Prefetch_parser_emits_one_direct_event_per_recorded_run()
    {
        var p = P("prefetch/SETUP.EXE-0A1B2C3D.pf");
        var sink = new ListSink();
        var r = new PrefetchParser().Parse(Item(p, "prefetch"), p, sink, default);
        Assert.Equal(EvidenceStatus.Success, r.Status);
        Assert.Equal(3, sink.Events.Count);
        Assert.All(sink.Events, e =>
        {
            Assert.Equal("Prefetch", e.Source);
            Assert.Equal(Classification.Direct, e.Classification);
            Assert.Equal("SETUP.EXE", e.Process);
            Assert.Equal("7", e.Fields["RunCount"]);
            Assert.Equal("0A1B2C3D", e.Fields["PrefetchHash"]);
        });
        Assert.Equal(new DateTimeOffset(SyntheticCorpus.Run1), sink.Events[0].Time.Utc);
        Assert.Equal("last run (prefetch)", sink.Events[0].TimeSemantics);
        Assert.Equal("previous run (prefetch)", sink.Events[2].TimeSemantics);
    }

    [Fact]
    public void Prefetch_from_an_unsupported_windows_version_and_truncated_files_fail_explicitly()
    {
        var old = Path.Combine(_dir, "old.pf");
        File.WriteAllBytes(old, SyntheticCorpus.Prefetch(version: 23));
        Assert.Equal(EvidenceStatus.Failed, new PrefetchParser().Parse(Item(old, "prefetch"), old, new ListSink(), default).Status);

        var cut = Path.Combine(_dir, "cut.pf");
        File.WriteAllBytes(cut, SyntheticCorpus.Prefetch()[..0x80]);
        var r = new PrefetchParser().Parse(Item(cut, "prefetch"), cut, new ListSink(), default);
        Assert.Equal(EvidenceStatus.Failed, r.Status);
        Assert.NotEmpty(r.Error);
    }

    // ---- LNK ---------------------------------------------------------------------------------------------------------------------

    [Fact]
    public void Lnk_target_arguments_working_directory_and_machine_are_decoded()
    {
        var p = P("lnk/SETUP.EXE.lnk");
        Assert.Equal("lnk", EvidenceFingerprint.Detect(p));
        var sink = new ListSink();
        var r = new LnkParser().Parse(Item(p, "lnk"), p, sink, default);
        Assert.Equal(EvidenceStatus.Success, r.Status);
        var e = Assert.Single(sink.Events);
        Assert.Equal(SyntheticCorpus.LnkTarget, e.Path);
        Assert.Equal("SETUP.EXE", e.Process);
        Assert.Equal(SyntheticCorpus.LnkArgs, e.Fields["Arguments"]);
        Assert.Equal(SyntheticCorpus.LnkWorkDir, e.Fields["WorkingDirectory"]);
        Assert.Equal(SyntheticCorpus.LnkMachine, e.Fields["MachineId"]);
        Assert.Equal("FIXED", e.Fields["DriveType"]);
    }

    [Fact]
    public void Lnk_truncated_or_zero_filled_fails()
    {
        var cut = Path.Combine(_dir, "cut.lnk");
        File.WriteAllBytes(cut, SyntheticCorpus.Lnk()[..90]);
        Assert.Equal(EvidenceStatus.Failed, new LnkParser().Parse(Item(cut, "lnk"), cut, new ListSink(), default).Status);
        File.WriteAllBytes(cut, new byte[200]);
        Assert.Equal(EvidenceStatus.Failed, new LnkParser().Parse(Item(cut, "lnk"), cut, new ListSink(), default).Status);
    }

    // ---- Registry ----------------------------------------------------------------------------------------------------------------

    [Fact]
    public void Registry_hives_are_recognised_and_readable_by_the_raw_reader()
    {
        foreach (var name in new[] { "registry/NTUSER.DAT", "registry/SOFTWARE" })
            Assert.Equal("regf", EvidenceFingerprint.Detect(P(name)));
        using var fs = File.OpenRead(P("registry/NTUSER.DAT"));
        var run = new RawRegistry(fs).OpenKey(@"Software\Microsoft\Windows\CurrentVersion\Run");
        Assert.NotNull(run);
        Assert.Equal(SyntheticCorpus.UserRunCommand, run!.Value("Updater")!.AsText);
        Assert.Equal(SyntheticCorpus.HiveWritten, run.LastWriteUtc);
        Assert.Null(new RawRegistry(fs).OpenKey(@"Software\Does\Not\Exist"));
    }

    [Fact]
    public void Ntuser_userassist_and_run_keys_become_events_and_a_userpath_finding()
    {
        var p = P("registry/NTUSER.DAT");
        var sink = new ListSink();
        var r = new UserHiveParser().Parse(Item(p, "ntuser_hive"), p, sink, default);
        Assert.Equal(EvidenceStatus.Success, r.Status);

        var ua = sink.Events.Where(e => e.Source == "UserAssist").ToList();
        Assert.Equal(2, ua.Count);                                         // the UEME_CTL control value is not a program
        var setup = Assert.Single(ua, e => e.Process == "SETUP.EXE");
        Assert.Equal(SyntheticCorpus.UserAssistProgram, setup.Path);
        Assert.Equal(new DateTimeOffset(SyntheticCorpus.HiveWritten), setup.Time.Utc);
        Assert.Equal("4", setup.Fields["RunCount"]);
        Assert.Equal("3", setup.Fields["FocusCount"]);
        Assert.Equal("61000", setup.Fields["FocusTimeMs"]);

        var run = Assert.Single(sink.Events, e => e.Source == "RunKey" && e.Fields["ValueName"] == "Updater");
        Assert.Equal(@"C:\Users\u\AppData\Roaming\synth\agent.exe", run.Path);
        Assert.Equal("agent.exe", run.Process);
        Assert.Single(sink.Events, e => e.Source == "RunKey" && e.Fields["Key"].EndsWith("RunOnce"));

        var f = Assert.Single(Correlation.Run(sink.Events), x => x.RuleId == "PERSIST-RUNKEY-USERPATH");
        Assert.Equal(@"C:\Users\u\AppData\Roaming\synth\agent.exe", f.File);
        Assert.Equal("T1547.001", f.MitreTechniqueId);
    }

    [Fact]
    public void Software_hive_run_keys_winlogon_and_ifeo_debugger_are_detected()
    {
        var p = P("registry/SOFTWARE");
        var sink = new ListSink();
        Assert.Equal(EvidenceStatus.Success, new SoftwareHiveParser().Parse(Item(p, "software_hive"), p, sink, default).Status);

        Assert.Contains(sink.Events, e => e.Source == "RunKey" && e.Fields["ValueName"] == "SecurityHealth");
        Assert.Contains(sink.Events, e => e.Source == "RunKey" && e.Fields["Key"].StartsWith("WOW6432Node") && e.Path == @"C:\ProgramData\agent\a.exe");
        Assert.Equal("true", Assert.Single(sink.Events, e => e.Source == "Winlogon" && e.Fields["ValueName"] == "Userinit").Fields["NonDefault"]);
        Assert.Equal("false", Assert.Single(sink.Events, e => e.Source == "Winlogon" && e.Fields["ValueName"] == "Shell").Fields["NonDefault"]);
        var ifeo = Assert.Single(sink.Events, e => e.Source == "IFEO");
        Assert.Equal("sethc.exe", ifeo.Fields["Target"]);

        var findings = Correlation.Run(sink.Events);
        Assert.Contains(findings, x => x.RuleId == "PERSIST-IFEO-DEBUGGER" && x.MitreTechniqueId == "T1546.012");
        Assert.Contains(findings, x => x.RuleId == "PERSIST-WINLOGON");
        Assert.DoesNotContain(findings, x => x.File.Contains("SecurityHealth"));
    }

    [Fact]
    public void A_hive_with_a_damaged_header_or_cell_is_a_parse_error_not_a_crash()
    {
        var bad = Path.Combine(_dir, "bad_hive");
        var bytes = SyntheticCorpus.NtUserHive();
        bytes[0] = (byte)'X';                                             // signature destroyed
        File.WriteAllBytes(bad, bytes);
        Assert.Throws<InvalidDataException>(() => { using var s = File.OpenRead(bad); _ = new RawRegistry(s); });

        File.WriteAllBytes(bad, SyntheticCorpus.NtUserHive()[..0x1100]); // bins cut off: root cell points outside the file
        using var s2 = File.OpenRead(bad);
        Assert.Throws<InvalidDataException>(() => new RawRegistry(s2).OpenKey(@"Software\Microsoft"));
    }

    // ---- Scheduled task ----------------------------------------------------------------------------------------------------------

    [Fact]
    public void Scheduled_task_xml_is_recognised_and_its_action_decoded()
    {
        var p = P("tasks/orchestratormaintain");
        Assert.Equal("task_xml", EvidenceFingerprint.Detect(p));
        var sink = new ListSink();
        Assert.Equal(EvidenceStatus.Success, new ScheduledTaskParser().Parse(Item(p, "task_xml"), p, sink, default).Status);
        var e = Assert.Single(sink.Events);
        Assert.Equal(SyntheticCorpus.TaskCommand, e.Path);
        Assert.Equal("updater_core.exe", e.Process);
        Assert.Equal(@"\orchestratormaintain", e.Task);
        Assert.Equal("true", e.Fields["Hidden"]);
        Assert.Equal("HighestAvailable", e.Fields["RunLevel"]);
        Assert.Equal(new DateTimeOffset(2026, 9, 19, 14, 58, 12, 500, TimeSpan.Zero), e.Time.Utc);
    }

    // ---- EVTX container ----------------------------------------------------------------------------------------------------------

    [Fact]
    public void Evtx_container_has_three_valid_chunks_with_consecutive_record_ids()
    {
        var p = P("evtx/container.evtx");
        Assert.Equal("evtx", EvidenceFingerprint.Detect(p));
        var chunks = EvtxRepair.Inspect(p);
        Assert.Equal(3, chunks.Count);
        Assert.All(chunks, c => Assert.True(c.Valid, c.Problem));
        Assert.Equal(1, chunks[0].FirstRecordId);
        Assert.Equal(30, chunks[2].LastRecordId);
    }

    [Fact]
    public void Evtx_damaged_chunk_is_found_dropped_and_the_record_gap_stays_visible()
    {
        var p = Path.Combine(_dir, "damaged.evtx");
        var b = SyntheticCorpus.EvtxContainer(3);
        b[4096 + 65536 + 512 + 100] ^= 0xFF;                               // flip a byte in chunk 1's record area
        File.WriteAllBytes(p, b);

        var bad = Assert.Single(EvtxRepair.Inspect(p), c => !c.Valid);
        Assert.Equal(1, bad.Index);
        Assert.Contains("CRC", bad.Problem);
        Assert.Equal((11, 20), (bad.FirstRecordId, bad.LastRecordId));

        var r = EvtxRepair.Repair(p, Path.Combine(_dir, "repaired.evtx"));
        Assert.Equal((3, 2), (r.TotalChunks, r.KeptChunks));
        var after = EvtxRepair.Inspect(r.OutputPath);
        Assert.All(after, c => Assert.True(c.Valid));
        Assert.Equal([1L, 21L], after.Select(c => c.FirstRecordId).ToArray());   // original IDs kept: the hole 11-20 is visible
        Assert.Equal(b, File.ReadAllBytes(p));                                    // the source file is never modified
    }

    [Fact]
    public void Evtx_non_evtx_input_is_rejected()
    {
        var f = Path.Combine(_dir, "x.evtx");
        File.WriteAllText(f, "not an event log");
        Assert.Throws<InvalidDataException>(() => EvtxRepair.Repair(f, Path.Combine(_dir, "y.evtx")));
    }
}
