services:
  api:
    build:
      context: ../../
      dockerfile: app/docker/Dockerfile.api

    env_file:
      - ../../.env
    depends_on:
      - postgres
      - redis
    ports:
      - "8000:8000"
    volumes:
      - document_data:/data/documents

  postgres:
    image: postgres:15-alpine
    container_name: idp-postgres
    environment:
      POSTGRES_DB: idp
      POSTGRES_USER: idp_user
      POSTGRES_PASSWORD: idp_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  
  redis:
    image: redis:7-alpine
    container_name: idp-redis
    ports:
      - "6379:6379"
  
  worker:
    build:
      context: ../../
      dockerfile: app/docker/Dockerfile.worker
    depends_on:
      - redis
      - postgres
    env_file:
      - ../../.env
    volumes:
      - document_data:/data/documents


volumes:
  postgres_data:
  document_data:
