name: Keep Alive Ping

on:
  schedule:
    # POSIX cron syntax: "At every 10th minute."
    - cron: '*/10 * * * *'
  workflow_dispatch:

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Web Service
        run: |
          curl -sS -m 10 https://devmind-backend-1hgt.onrender.com/health > /dev/null
          echo "Ping sent successfully!"