<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Balsam.Inventory.Domain\Balsam.Inventory.Domain.csproj" />
    <ProjectReference Include="..\Balsam.Inventory.Application\Balsam.Inventory.Application.csproj" />
    <ProjectReference Include="..\..\..\Balsam.SharedKernel\Balsam.SharedKernel.csproj" />
    <ProjectReference Include="..\..\..\Balsam.Infrastructure\Balsam.Infrastructure.csproj" />
  </ItemGroup>

</Project>
