using LogAnalyzer.Dfir.Model;

namespace LogAnalyzer.Dfir.Analysis;

/// <summary>
/// Contract data for one finding rule: what kind of claim it makes, its plain-language meaning, the limits of the method,
/// the evidence it cannot see and the next steps. <see cref="ContradictionCheck"/> names the contradiction test the rule
/// really performs; null means the rule does not test for contradicting evidence (said so in the finding's Limitations).
/// </summary>
public sealed record RuleContract(
    string RuleId, string Producer, Func<Finding, SemanticType> Semantic, string Meaning,
    IReadOnlyList<string> Limitations, IReadOnlyList<string> MissingEvidence, IReadOnlyList<string> NextSteps, string? ContradictionCheck = null)
{
    public const string RuleVersion = "1.0";
}

public static class RuleContracts
{
    private const string Corr = "LogAnalyzer.Dfir.Analysis.Correlation";
    private const string Live = "LogAnalyzer.Dfir.Windows.Investigation.LiveStateAnalyzer";
    private const string W11 = "LogAnalyzer.Dfir.Analysis.Wp11Rules";
    private const string Pol = "LogAnalyzer.Dfir.Analysis.PolicyTimeline";
    private const string W14 = "LogAnalyzer.Dfir.Analysis.Wp14Rules";
    private const string Seq = "LogAnalyzer.Dfir.Analysis.SequenceRules";
    private const string Cont = "LogAnalyzer.Dfir.Windows.Containment.ProcessContainmentService";

    private static RuleContract R(string id, string producer, SemanticType t, string meaning, string[] limits, string[] missing, string[] steps, string? contra = null) =>
        new(id, producer, _ => t, meaning, limits, missing, steps, contra);

    private static RuleContract RF(string id, string producer, Func<Finding, SemanticType> t, string meaning, string[] limits, string[] missing, string[] steps, string? contra = null) =>
        new(id, producer, t, meaning, limits, missing, steps, contra);

    public static IReadOnlyList<RuleContract> All { get; } =
    [
        R("DEF-DETECTION", Corr, SemanticType.Observation, "Antivirusul Windows a înregistrat o detecție; asta nu arată că programul a rulat.",
            ["O detecție de către Defender nu dovedește execuția și nu exclude fals-pozitive."],
            ["Dacă fișierul a rulat înainte de detecție (Prefetch, BAM, EVTX 4688).", "Rezultatul remedierii (curățat/pus în carantină)."],
            ["Verificați dacă fișierul mai există și dacă rulează.", "Căutați același hash pe alte stații."]),
        R("DEF-TAMPER", Corr, SemanticType.Configuration, "Jurnalul Defender arată protecție dezactivată sau excluderi adăugate.",
            ["Arată o schimbare de configurație, nu cine a făcut-o și nici dacă a fost abuzată."],
            ["Contul și procesul care au modificat setarea.", "Starea actuală a protecției."],
            ["Stabiliți cine a modificat setarea (Security 4688/4657) și dacă excluderea are justificare."]),
        R("LOG-TAMPER", Corr, SemanticType.Observation, "Windows a înregistrat ștergerea unui jurnal, oprirea jurnalizării sau schimbarea politicii de audit.",
            ["Ștergerea e dovedită; intenția rău-voitoare nu este (mentenanța o produce și ea).", "Activitatea dinaintea ștergerii nu mai e în jurnalul respectiv."],
            ["Activitatea anterioară ștergerii (SRUM, Prefetch, Amcache, copii VSS)."],
            ["Cereți ticketul de mentenanță, dacă există.", "Căutați copii ale jurnalului (VSS, SIEM, export)."]),
        R("LOG-GAP", Corr, SemanticType.Inference, "Numerele de înregistrare au goluri mari; asta sugerează ștergere selectivă, nu o dovedește.",
            ["Deducție din numerotare; golurile apar și la corupere sau la export parțial."],
            ["Un export complet al jurnalului sau o copie VSS pentru comparație."],
            ["Comparați cu o copie a jurnalului din altă sursă.", "Verificați integritatea fișierului EVTX."]),
        R("PERSIST-SERVICE-USERPATH", Corr, SemanticType.Configuration, "Un serviciu a fost instalat cu binarul într-o locație scriabilă de utilizatori.",
            ["Instalarea nu înseamnă că serviciul a pornit sau a făcut ceva.", "Locațiile scriabile sunt folosite și de software legitim."],
            ["Pornirile serviciului (System 7036), Prefetch pentru binar, semnătura binarului."],
            ["Verificați semnătura și hash-ul binarului.", "Verificați cine a instalat serviciul (cont din eveniment)."]),
        R("PERSIST-TASK", Corr, SemanticType.Configuration, "A fost creat un task programat care indică o locație scriabilă sau un script.",
            ["Crearea nu înseamnă că taskul a rulat."],
            ["Rulările taskului (TaskScheduler 200/201) și Prefetch pentru executabil."],
            ["Verificați acțiunea completă a taskului și contul care l-a creat."]),
        R("PERSIST-TASK-CONFIG", Corr, SemanticType.Configuration, "Definiția unui task programat arată o acțiune dintr-o locație scriabilă.",
            ["Arată configurația, nu o rulare.", "Autorul și data de înregistrare sunt scrise de creator."],
            ["Rulările taskului (TaskScheduler 200/201) sau Prefetch pentru executabil."],
            ["Căutați rulări ale taskului în jurnale.", "Verificați semnătura executabilului."], "taskul este dezactivat (Settings/Enabled=false)"),
        R("PERSIST-SERVICE-CONFIG", Corr, SemanticType.Configuration, "Un serviciu din hive-ul SYSTEM are binarul sau ServiceDll într-o locație scriabilă.",
            ["Arată configurația, nu o pornire sau o instalare la o anumită dată."],
            ["Instalarea (System 7045), pornirile (7036), semnătura binarului."],
            ["Verificați binarul (hash, semnătură) și evenimentele de instalare."], "serviciul este dezactivat (Start=4)"),
        R("FIREWALL-RULE-USERPATH", Corr, SemanticType.Configuration, "O regulă de firewall permite un program dintr-o locație scriabilă.",
            ["Arată o regulă, nu trafic efectiv.", "Aplicațiile per utilizator își adaugă astfel de reguli la instalare."],
            ["Trafic efectiv al programului (firewall 5156, SRUM)."],
            ["Verificați programul și dacă regula mai există."]),
        R("PERSIST-RUNKEY-USERPATH", Corr, SemanticType.Configuration, "O cheie Run/RunOnce pornește un program dintr-o locație scriabilă.",
            ["Arată configurația; ora este a cheii, nu a valorii.", "Multe aplicații legitime per utilizator se pornesc așa."],
            ["Dovada că intrarea a rulat (Prefetch, BAM)."],
            ["Verificați programul indicat (hash, semnătură)."]),
        R("PERSIST-IFEO-DEBUGGER", Corr, SemanticType.Configuration, "Image File Execution Options redirecționează pornirea unui program către alt program.",
            ["Arată configurația, nu o redirecționare efectivă."],
            ["Dovada că programul țintă a fost pornit prin redirecționare (Prefetch)."],
            ["Verificați dacă depanatorul este instalat intenționat."]),
        R("PERSIST-WINLOGON", Corr, SemanticType.Configuration, "Shell sau Userinit din Winlogon diferă de valoarea implicită.",
            ["Arată configurația, nu o rulare."],
            ["Dovada că programul a pornit la autentificare (Prefetch)."],
            ["Verificați valoarea față de configurația standard a stației."]),
        R("EXEC-USERPATH", Corr, SemanticType.Execution, "Programe au rulat din locații scriabile; singure, sunt frecvente pentru instalatoare și aplicații per utilizator.",
            ["Execuția provine din Prefetch/BAM; intrările Amcache arată doar prezența.", "Locația scriabilă nu face programul rău-intenționat."],
            ["Semnătura și hash-ul programului, originea lui (descărcare)."],
            ["Verificați semnătura și originea celor mai recente programe."]),
        R("EXEC-SCRIPT-VIA-LOLBIN", Corr, SemanticType.Execution, "Un instrument Windows frecvent abuzat a rulat și a referit scripturi din locații scriabile.",
            ["Fișierele referite în Prefetch nu dovedesc că scripturile au fost executate sau ce conțineau."],
            ["Conținutul scriptului (PowerShell 4104), linia de comandă (4688)."],
            ["Recuperați scriptul și analizați-l.", "Căutați linia de comandă în jurnale."]),
        R("EXEC-USERPATH-CORRELATED", Corr, SemanticType.Correlation, "Un program rulat din locație scriabilă apare lângă alte constatări grave, în timp sau în cale.",
            ["Apropierea în timp sau în cale nu dovedește legătura cauzală dintre constatări."],
            ["Dovada directă a legăturii (proces părinte, linie de comandă)."],
            ["Reconstituiți relația proces-părinte/copil din jurnale."]),
        RF("NET-LOLBIN-TRAFFIC", Corr, f => f.Classification == Classification.Correlated ? SemanticType.Correlation : SemanticType.Inference,
            "O unealtă Windows abuzată frecvent a transferat volume mari prin rețea (SRUM).",
            ["SRUM arată volume pe interval orar, nu destinații sau conținut.", "Corelarea cu Prefetch arată că programul a rulat, nu că traficul a fost malițios."],
            ["Destinațiile traficului (captură de rețea, jurnale firewall/proxy)."],
            ["Obțineți destinațiile din firewall/proxy/PCAP.", "Verificați dacă transferul corespunde unei activități legitime."]),
        RF("NET-USERPATH-UPLOAD", Corr, f => f.Classification == Classification.Correlated ? SemanticType.Correlation : SemanticType.Inference,
            "Un program din locație scriabilă a trimis volum mare de date (SRUM).",
            ["SRUM arată volume pe interval orar, nu destinații sau conținut.", "Sincronizarea în cloud legitimă produce același tipar."],
            ["Destinațiile traficului (captură de rețea, jurnale firewall/proxy)."],
            ["Obțineți destinațiile din firewall/proxy/PCAP.", "Verificați programul (semnătură, origine)."]),
        R("CRED-BRUTEFORCE", Corr, SemanticType.Observation, "Au fost înregistrate multe autentificări eșuate pentru același cont și adresă.",
            ["Nu arată dacă o autentificare ulterioară a reușit sau dacă atacul a avut succes."],
            ["Autentificări reușite ulterioare (4624) de la aceeași adresă."],
            ["Verificați 4624 de la aceeași adresă după serie.", "Blocați sau monitorizați adresa dacă e externă."]),
        R("REMOTE-RDP-PUBLIC", Corr, SemanticType.Observation, "Au fost înregistrate autentificări RDP de la adrese publice.",
            ["Adresa din eveniment poate fi un intermediar; nu identifică persoana."],
            ["Activitatea din sesiune (procese, fișiere), jurnalele gateway-ului RDP."],
            ["Confirmați cu utilizatorul legitimitatea accesului.", "Verificați activitatea din sesiunile respective."]),
        R("PS-SUSPICIOUS", Corr, SemanticType.Inference, "Blocuri PowerShell conțin cuvinte-cheie folosite des în descărcare, obfuscare sau dezactivare a protecției.",
            ["Potrivire de cuvinte-cheie; instrumentele administrative legitime le folosesc.", "Nu arată rezultatul execuției."],
            ["Contextul scriptului: cine, de unde, ce a făcut."],
            ["Citiți scriptul complet.", "Identificați contul și procesul care l-au lansat."]),
        R("DOWNLOAD-THEN-EXEC", Corr, SemanticType.Correlation, "O descărcare a fost urmată, în 6 ore, de rularea unui program din același folder.",
            ["Corelație în timp și în cale, nu dovadă că programul rulat este fișierul descărcat."],
            ["Zone.Identifier al fișierului extras; jurnalul de extragere al arhivei."],
            ["Comparați hash-ul fișierului descărcat cu cel al programului rulat."]),
        RF("INCIDENT-CHAIN", Corr, _ => SemanticType.Correlation, "Constatări grave din surse diferite sunt grupate în aceeași fereastră de timp.",
            ["Gruparea în timp nu demonstrează legătura cauzală dintre pași."],
            ["Dovada legăturii dintre pași (proces părinte, hash comun)."],
            ["Reconstituiți fiecare pas din probele indicate.", "Stabiliți ce date au părăsit stația în fereastra lanțului."],
            "contradicțiile pașilor sunt preluate în lanț"),
        R("LIVE-UNSIGNED-USERPATH", Live, SemanticType.Execution, "Un proces nesemnat rulează acum dintr-o locație scriabilă (fotografie a stării live).",
            ["Fotografia arată starea la momentul colectării, nu istoricul.", "Software legitim per utilizator poate fi nesemnat."],
            ["Istoricul rulărilor (Prefetch, BAM), originea fișierului."],
            ["Izolați programul pentru scanare completă.", "Verificați hash-ul și originea."]),
        R("LIVE-UNSIGNED-USERPATH-NET", Live, SemanticType.Execution, "Un proces nesemnat dintr-o locație scriabilă rulează acum și are conexiuni în Internet.",
            ["Conexiunile sunt cele din momentul colectării; scopul lor nu e cunoscut."],
            ["Destinațiile în timp (firewall, PCAP), istoricul rulărilor."],
            ["Izolați programul pentru scanare completă.", "Obțineți istoricul conexiunilor."]),
        R("LIVE-SERVICE-USERPATH", Live, SemanticType.Configuration, "Un serviciu este configurat acum cu binarul într-o locație scriabilă.",
            ["Arată configurația curentă, nu istoricul instalării."],
            ["Evenimentele de instalare și pornire, semnătura binarului."],
            ["Verificați binarul și evenimentele de instalare."], "serviciul este dezactivat (StartMode=Disabled)"),
        R("LIVE-TASK-USERPATH", Live, SemanticType.Configuration, "Un task programat actual rulează o comandă dintr-o locație scriabilă.",
            ["Arată configurația curentă, nu o rulare."],
            ["Rulările taskului (TaskScheduler 200/201)."],
            ["Verificați comanda și contul taskului."]),
        R("LIVE-AUTORUN-USERPATH", Live, SemanticType.Configuration, "O cheie Run actuală pornește un program dintr-o locație scriabilă.",
            ["Arată configurația curentă; multe aplicații legitime per utilizator procedează la fel."],
            ["Dovada că intrarea a rulat (Prefetch, BAM)."],
            ["Verificați programul indicat."]),
        R("CONTAIN-SUSPICIOUS-PROGRAM", Cont, SemanticType.Observation, "Scanarea unui program izolat a găsit motive de suspiciune (semnătură, locație, conexiuni, persistență).",
            ["Motivele sunt observații la momentul scanării; nu dovedesc intenția.", "Software legitim nesemnat declanșează aceleași motive."],
            ["Istoricul programului, originea lui, rezultate ale altor scanere."],
            ["Verificați destinațiile din raport.", "Căutați același SHA-256 pe alte stații."]),
        R("CONTAIN-BLOCKED-ATTEMPTS", Cont, SemanticType.Observation, "Windows a înregistrat încercări de comunicare blocate după izolarea programului.",
            ["Arată încercări blocate, nu ce ar fi transmis programul."],
            ["Destinațiile finale și conținutul intenționat."],
            ["Analizați destinațiile încercate.", "Păstrați izolarea până la clarificare."]),
        R("CONTAIN-EXTERNAL-CONNECTIONS", Cont, SemanticType.Observation, "Programul avea conexiuni către Internet la momentul izolării.",
            ["Tabela TCP e o fotografie; scopul conexiunilor nu e cunoscut."],
            ["Istoricul conexiunilor și conținutul."],
            ["Verificați destinațiile.", "Păstrați izolarea până la clarificare."]),
        R("CONTAIN-PERSISTENCE", Cont, SemanticType.Configuration, "Există intrări de autostart care conțin calea sau numele programului.",
            ["Arată configurația de autostart, nu o pornire efectivă."],
            ["Dovada pornirilor trecute."],
            ["Dezactivați intrările după preluarea probelor, nu înainte."]),
        // ---- WP11 Tier 1 ----
        R("SMB-ADMIN-SHARE", W11, SemanticType.Observation, "Windows a înregistrat accesul la o partajare administrativă (C$, ADMIN$, IPC$) dintr-o altă adresă.",
            ["Accesul la partajări administrative este rutină pentru administratori și software de backup; evenimentul nu spune dacă contul este autorizat.", "Se numără accesele; pragurile de volum nu fac parte din această regulă.",
             "5145 apare doar dacă auditul de partajări detaliat este activ; lipsa lui nu arată că nu s-au accesat fișiere."],
            ["Autentificarea care a precedat accesul (4624 tip 3) și jurnalele stației sursă.", "Auditul detaliat de partajări (5145), dacă nu este activ."],
            ["Verificați dacă contul și stația sursă sunt administrative autorizate.", "Căutați creări de servicii (7045) și procese noi în aceeași fereastră."]),
        R("SMB-SHARE-PERMS-CHANGED", W11, SemanticType.Observation, "Permisiunile unui obiect de tip fișier sau director (inclusiv partajat) au fost schimbate (4670).",
            ["4670 nu spune dacă schimbarea a fost intenționată; instalatoarele și moștenirea permisiunilor o produc și ele.", "Acordările largi sunt detectate doar din descriptorii vechi și noi din eveniment."],
            ["Procesul și sesiunea care au făcut schimbarea, motivul operațional.", "Starea actuală a permisiunilor."],
            ["Comparați descriptorul nou cu politica de acces a partajării.", "Verificați cine a avut acces după schimbare."]),
        R("ACCOUNT-CREATED", W11, SemanticType.Observation, "A fost creat un cont (4720); creat nu înseamnă folosit.",
            ["Evenimentul arată crearea, nu folosirea; folosirea se citește din autentificările colectate, care pot lipsi.", "Un cont creat și nefolosit în dovezile colectate poate fi folosit în afara perioadei sau a surselor colectate."],
            ["Autentificările contului (4624/4648) din perioade sau de pe alte stații necolectate.", "Cine a cerut contul (ticket)."],
            ["Confirmați cererea de creare a contului.", "Căutați autentificările contului pe controlerul de domeniu."]),
        R("ACCOUNT-ADDED-PRIVILEGED-GROUP", W11, SemanticType.Observation, "Un cont a fost adăugat într-un grup privilegiat (Administrators, Domain Admins, Remote Desktop Users…).",
            ["Arată apartenența acordată, nu folosirea ei și nici cine a cerut-o.", "Lista grupurilor privilegiate este o listă de date; un grup necunoscut ei nu este semnalat."],
            ["Aprobarea modificării, autentificările contului după adăugare."],
            ["Verificați aprobarea pentru adăugare.", "Căutați folosirea contului după adăugare (4624, 4672)."]),
        R("ACCOUNT-CREATED-THEN-USED", W11, SemanticType.Observation, "Un cont creat în caz a fost folosit ulterior (4624/4648); High doar dacă este și privilegiat și folosit de la distanță.",
            ["Corelație în timp și după SID/nume în același jurnal; nu dovedește că utilizatorul nu este cel legitim.", "Dacă SID-ul lipsește, legătura după nume nu exclude refolosirea numelui.", "Folosirea de la distanță se deduce din tipul de logon și adresa sursă din 4624."],
            ["Sursa independentă (stația de unde s-a autentificat contul), cererea de creare."],
            ["Confirmați cu proprietarul contului.", "Verificați activitatea din sesiunile contului."]),
        R("REMOTE-RDP-INTERNAL", W11, SemanticType.Observation, "Au fost înregistrate sesiuni RDP din rețeaua internă (4624 tip 10, TerminalServices 21/22/25/1149).",
            ["Sesiunea RDP internă este administrare obișnuită; evenimentul nu arată ce s-a făcut în sesiune.", "Adresa sursă poate fi un gateway sau un tunel (loopback); nu identifică persoana.",
             "Sursele publice sunt tratate de REMOTE-RDP-PUBLIC."],
            ["Activitatea din sesiune (procese, fișiere), jurnalele stației sursă."],
            ["Confirmați cu utilizatorul legitimitatea sesiunilor.", "Verificați procesele pornite în sesiunile respective."]),
        R("REMOTE-WINRM", W11, SemanticType.Observation, "Au fost înregistrate sesiuni WinRM (WinRM/Operational 6/91/142) sau pornirea gazdei de sesiune wsmprovhost.exe.",
            ["WinRM este folosit legitim de instrumente de administrare; evenimentele nu arată comenzile rulate.", "Evenimentul 6 este o sesiune pornită de această stație, nu un acces primit.",
             "Canalul WinRM/Operational poate lipsi (indisponibil) pe unele versiuni sau configurații."],
            ["Scripturile și comenzile din sesiune (PowerShell 4104, 4688), stația sursă."],
            ["Identificați sursa sesiunii din autentificarea de tip 3.", "Citiți blocurile PowerShell din aceeași fereastră."]),
        R("REMOTE-PSEXEC", W11, SemanticType.Configuration, "Un serviciu tipic execuției la distanță (PSEXESVC sau cu binarul în folderul Windows / pe ADMIN$) a fost instalat, eventual după copierea executabilului pe ADMIN$.",
            ["Instalarea serviciului nu dovedește ce a rulat prin el; indică, nu dovedește, execuție la distanță.", "Numele aleatoriu este o euristică de formă (binar direct în folderul Windows); instrumente legitime de gestiune pot instala astfel.",
             "Fără 5145 (audit de partajări detaliat) nu se poate lega serviciul de copierea fișierului."],
            ["Procesul pornit de serviciu (4688 / Sysmon 1), hash-ul binarului, stația sursă a conexiunii SMB."],
            ["Identificați stația sursă din 5145/4624.", "Căutați procesele copil ale serviciului."]),
        R("REMOTE-SSH", W11, SemanticType.Observation, "OpenSSH a înregistrat autentificări acceptate de la distanță (OpenSSH/Operational 4).",
            ["Arată o autentificare acceptată, nu activitatea din sesiune.", "Canalul OpenSSH/Operational există doar dacă OpenSSH este instalat; absența lui nu arată că nu s-a folosit SSH."],
            ["Comenzile rulate în sesiune (4688 / Sysmon 1), cheile autorizate."],
            ["Verificați contul și sursa.", "Verificați authorized_keys și configurația sshd."]),
        R("SECURITY-AGENT-STOPPED", W11, SemanticType.Observation, "Un produs de securitate cunoscut (antivirus, EDR, Sysmon) a fost oprit, dezactivat, dezinstalat sau reconfigurat.",
            ["Evenimentul nu arată cine sau de ce; actualizările, repornirile și dezinstalările planificate produc aceleași evenimente.", "Lista produselor este o listă de date; un produs necunoscut ei nu este semnalat.",
             "Este distinctă de DEF-TAMPER (jurnalul Defender): aici se citesc evenimentele de serviciu și de instalare."],
            ["Contul și procesul care au oprit serviciul (Security 4688/4656), starea actuală a produsului.", "Dovezi de activitate a produsului după eveniment (telemetrie EDR)."],
            ["Stabiliți cine a oprit produsul și dacă a fost o mentenanță.", "Verificați dacă produsul rulează acum și când a transmis ultima dată telemetrie."],
            "oprirea coincide cu o oprire/repornire a sistemului sau serviciul a fost pornit din nou în fereastra de repornire"),
        R("VSS-SNAPSHOT-DELETED", W11, SemanticType.Execution, "A fost înregistrată o comandă care șterge copiile shadow (VSS); comanda lansată nu înseamnă ștergere reușită.",
            ["Linia de comandă arată lansarea comenzii, nu rezultatul ei și nici ce copii existau.", "Evenimentele volsnap 25/33 au și cauze benigne (limita de spațiu); erorile VSS 8193/8194 sunt doar probe de sprijin.",
             "High numai cu dovezi de impact deja existente în caz (constatare de impact, T1486/T1485 sau detecție Defender de ransomware în ±24 h); nu există un detector propriu de criptare."],
            ["Existența copiilor înainte și după (vssadmin list shadows, copii în VSS), activitatea de modificare în masă a fișierelor (USN)."],
            ["Verificați dacă copiile mai există.", "Căutați modificări în masă sau redenumiri de fișiere în aceeași fereastră."]),
        R("DNS-RARE-DOMAIN", W11, SemanticType.Observation, "Un domeniu rar în caz a fost rezolvat de o unealtă Windows abuzată frecvent sau de un proces dintr-o locație scriabilă.",
            ["Rezolvarea unui nume nu dovedește o conexiune sau un transfer.", "Rar înseamnă rar în dovezile acestui caz (cel mult N apariții), nu rar în general.",
             "În DNS-Client 3006/3008/3020 procesul este dedus din PID și poate fi greșit (PID-urile se reutilizează); Sysmon 22 numește procesul direct.",
             "Pragul este un număr de apariții, nu un model statistic; nu clasifică tunelarea DNS (DnsTunnelingClassifier nu este conectat aici)."],
            ["Conexiunea efectivă (firewall 5156, Sysmon 3, PCAP) și răspunsul DNS.", "Reputația domeniului și proprietarul lui."],
            ["Verificați domeniul și adresa rezolvată.", "Căutați conexiuni ale procesului către adresa rezolvată."]),
        R("DNS-SERVER-CHANGED", W11, SemanticType.Configuration, "Serverele DNS configurate pentru o interfață au fost diferite în valorile NameServer colectate.",
            ["Arată valorile, nu cine sau când le-a schimbat (ora este a cheii sau a colectării).", "Jurnalul NetworkProfile nu conține servere DNS; fără o colectare a cheilor NameServer regula nu are ce citi.",
             "Schimbarea rețelei (DHCP, VPN) schimbă legitim serverele DNS."],
            ["Istoricul configurației DNS (DHCP-Client, copii ale registrului), politica de rețea așteptată."],
            ["Comparați serverele cu cele ale organizației.", "Verificați dacă schimbarea coincide cu o mutare între rețele sau cu o conexiune VPN."]),
        R("REMOTE-TOOL-PRESENT", W11, SemanticType.Presence, "Există artefacte (Amcache/ShimCache, serviciu, instalare, fișiere de log) ale unei unelte de acces la distanță; prezent nu înseamnă executat.",
            ["Prezența unui artefact nu dovedește execuția sau o sesiune.", "Lista uneltelor este o listă de date; o unealtă necunoscută ei nu este semnalată.", "Software aprobat în profil este Info (aprobat în profil)."],
            ["Artefacte de execuție (Prefetch, BAM, 4688, Sysmon 1), jurnalele propriei unelte, conexiunile de rețea."],
            ["Verificați dacă unealta este aprobată și instalată de organizație.", "Căutați artefacte de execuție și sesiuni în jurnalele uneltei."]),
        R("REMOTE-TOOL-EXECUTED", W11, SemanticType.Execution, "Un artefact de execuție arată că o unealtă de acces la distanță a rulat.",
            ["Execuția unealtei nu arată o sesiune, un partener conectat sau cine a pornit-o.", "Lista uneltelor este o listă de date; software aprobat în profil este Info (aprobat în profil).",
             "O copie portabilă într-o altă cale decât cea aprobată în profil nu este considerată aprobată."],
            ["Jurnalele propriei unelte (sesiuni, parteneri), conexiunile de rețea, contul care a pornit-o."],
            ["Confirmați cu utilizatorul și cu suportul IT.", "Obțineți jurnalele uneltei pentru lista sesiunilor."]),
        R("POLICY-CONTROL-GAP", Pol, SemanticType.Correlation, "O setare cerută de politica așteptată nu este observată la unul din nivelurile aplicat, impus sau observat.",
            ["Compară politica așteptată cu dovezi de aplicare (GroupPolicy/Operational), de stare efectivă și cu evenimente; un nivel necolectat e UNKNOWN și nu produce decalaj.",
             "Absența evenimentelor poate însemna absența activității auditate, nu absența auditului.", "Nu arată cine sau de ce, nici dacă decalajul e intenționat."],
            ["Starea efectivă a setării (auditpol /get, AuditQuerySystemPolicy).", "GroupPolicy/Operational de la stație și conținutul GPO din SYSVOL (gpresult / RSoP)."],
            ["Rulați gpresult /h și auditpol /get pe stație.", "Verificați replicarea SYSVOL, filtrarea de securitate, filtrul WMI și politica loopback."]),
        R("MEDIA-AUTHORIZED", W14, SemanticType.Presence, "Un mediu amovibil observat este în registrul de medii, activ, valabil la momentul observat, iar utilizatorul și zona se potrivesc (sau registrul nu le cere).",
            ["Compară seria observată cu registrul; nu arată ce s-a făcut cu mediul (prezență, nu copiere).", "Utilizatorul se știe doar când o sursă îl conține (de exemplu Security 6416); altfel starea nu poate fi AUTHORIZED dacă registrul atribuie un utilizator.",
             "Registrul este introdus de operator; nu este verificat față de un inventar fizic."],
            ["Activitatea pe volum (LNK/JumpList, 4663, USN) și hash-urile fișierelor.", "Dovada că registrul era în vigoare la momentul observat (istoricul registrului este în jurnalul de audit al registrelor)."],
            ["Confirmați că registrul de medii este actual.", "Verificați activitatea pe volum dacă mediul este clasificat."]),
        R("MEDIA-REGISTERED", W14, SemanticType.Presence, "Un mediu observat este în registru, dar utilizatorul, zona, valabilitatea sau VID/PID nu se potrivesc ori nu pot fi confirmate.",
            ["Neconfirmarea utilizatorului sau a zonei poate veni din lipsa sursei (6416 absent, zonă nedeclarată), nu dintr-o abatere dovedită.", "Prezența nu este copiere."],
            ["Contul care a folosit mediul (Security 6416 / 4663), zona sistemului declarată de operator."],
            ["Declarați zona sistemului și verificați utilizatorul din jurnalele Security.", "Corectați registrul dacă atribuirea s-a schimbat."]),
        R("MEDIA-UNREGISTERED", W14, SemanticType.Presence, "Un mediu amovibil observat nu are seria în registrul de medii (definit).",
            ["Seria vine din USBSTOR / Partition/Diagnostic / PnP; serii duplicate sau reutilizate de unii producători pot da potriviri false.", "Un registru incomplet produce aceeași constatare pentru un mediu legitim.", "Prezența nu este copiere."],
            ["Inventarul fizic al mediilor, aprobarea de utilizare, activitatea pe volum."],
            ["Identificați mediul și proprietarul.", "Căutați activitatea pe volum (MEDIA-FILE-ACTIVITY)."]),
        R("MEDIA-UNAUTHORIZED", W14, SemanticType.Presence, "Un mediu observat este în registru, dar retras / distrus sau observat în afara perioadei de valabilitate.",
            ["Registrul nu are data retragerii: observația poate fi anterioară retragerii.", "Valabilitatea se compară în zile UTC cu orele observațiilor.", "Prezența nu este copiere."],
            ["Data retragerii sau distrugerii, documentul de predare, activitatea pe volum."],
            ["Verificați dacă mediul a fost folosit după retragere.", "Căutați activitatea pe volum."]),
        R("MEDIA-UNKNOWN", W14, SemanticType.Presence, "Un mediu observat nu poate fi comparat cu registrul: fără serie sau registru nedefinit.",
            ["Un registru fără rânduri este „registru nedefinit”, nu un rezultat de conformitate.", "Fără serie, mediul nu poate fi identificat."],
            ["Registrul de medii definit, seria mediului (din Partition/Diagnostic sau Security 6416)."],
            ["Definiți registrul de medii.", "Recolectați sursele care conțin seria (Partition/Diagnostic, Security 6416)."]),
        R("MEDIA-FILE-ACTIVITY", W14, SemanticType.Observation, "Există urme de acces sau scriere de fișiere pe litera de unitate a unui mediu amovibil (LNK, JumpList, Security 4663, USN).",
            ["Litera de unitate vine din MountedDevices (ultima asociere) și poate fi reatribuită altui volum.", "Scrierea este susținută doar de 4663 cu mască de scriere sau de USN cu creare/extindere; LNK și JumpList arată referirea unui fișier, nu direcția.",
             "Nu arată conținutul, hash-ul sau ținta copierii."],
            ["Hash-urile fișierelor, jurnalul USN al volumului amovibil, 4663 cu SACL pe fișierele sensibile."],
            ["Examinați volumul mediului dacă este disponibil.", "Corelați cu clasificarea fișierelor atinse."]),
        R("MEDIA-OPTICAL-ACTIVITY", W14, SemanticType.Presence, "Există urme de CD/DVD (unitate optică, IMAPI, LNK cu volum CDROM, imagine .iso montată, instrument de inscripționare); tratat separat de USB.",
            ["Prezența unei unități, a unei imagini sau a unui instrument nu arată că s-a scris un disc; inscripționarea se susține doar din IMAPI sau dintr-un instrument executat.", "Un disc optic nu are serie în aceste surse: nu se poate compara cu registrul.",
             "ID-urile evenimentelor de montare (VHDMP / Storage) variază cu versiunea Windows și nu sunt fixate; sunt citite după extensia imaginii."],
            ["Conținutul discului, jurnalele instrumentului de inscripționare, registrul discurilor (serie imposibilă)."],
            ["Verificați dacă discul a fost predat și înregistrat.", "Obțineți jurnalele instrumentului de inscripționare."]),
        R("AIRGAP-NETWORK-CONNECTED", W14, SemanticType.Observation, "Un profil de rețea a fost conectat (NetworkProfile 10000) pe un sistem air-gapped sau autonom.",
            ["Arată conectarea, nu ce s-a transferat și nu dacă rețeaua avea ieșire în afară.", "Autorizarea vine din destinațiile și canalele profilului de proceduri; fără ele, rămâne „conectivitate observată, necesită explicație”.",
             "Durata se calculează doar dacă deconectarea (10001) a fost colectată."],
            ["Traficul (firewall 5156, PCAP), adaptorul folosit, aprobarea conectării."],
            ["Cereți explicația conectării.", "Verificați ce s-a transferat în fereastra de timp (Security 5156, SRUM)."]),
        R("AIRGAP-WIFI-ASSOCIATED", W14, SemanticType.Observation, "S-a asociat o conexiune Wi-Fi (WLAN-AutoConfig 8001 / 11001 / 11005) pe un sistem air-gapped sau autonom.",
            ["Arată asocierea la rețeaua radio, nu traficul.", "Încercările eșuate (11000, 11002–11004 fără 8001/11001/11005) nu sunt raportate ca asociere.", "Canalul WLAN-AutoConfig poate lipsi pe sisteme fără Wi-Fi."],
            ["Traficul în fereastră, BSSID-ul, adaptorul și cine l-a activat."],
            ["Identificați SSID-ul și proprietarul lui.", "Verificați activitatea de rețea în fereastră."]),
        R("AIRGAP-BLUETOOTH-PAIRED", W14, SemanticType.Observation, "Un dispozitiv Bluetooth are nod de dispozitiv (BTHENUM / BTHLE) sau eveniment de asociere pe un sistem air-gapped sau autonom.",
            ["Nodul arată că dispozitivul a fost asociat sau descoperit, nu ce s-a transmis.", "Evenimentele de asociere sunt colectate doar dacă canalele Bluetooth există și sunt activate.", "Radioul Bluetooth în sine este raportat de AIRGAP-NIC-ADDED."],
            ["Tipul dispozitivului (tastatură, telefon), transferurile Bluetooth."],
            ["Identificați dispozitivul după adresă.", "Verificați dacă un telefon sau un modem era asociat."]),
        R("AIRGAP-DHCP-LEASE", W14, SemanticType.Observation, "Clientul DHCP a înregistrat activitate (50036, 50037, 50065, 1103) pe un sistem air-gapped sau autonom.",
            ["Semnificația exactă a ID-ului depinde de versiunea Windows; unele raportează reînnoiri sau eșecuri.", "Adresa, serverul și gateway-ul sunt citate doar dacă evenimentul le conține.", "Un server DHCP local poate atribui legitim adrese."],
            ["Adresa atribuită, serverul DHCP, interfața, traficul."],
            ["Comparați adresa și serverul cu rețeaua aprobată.", "Verificați interfața și conexiunea asociată (NetworkProfile)."]),
        R("AIRGAP-NIC-ADDED", W14, SemanticType.Observation, "Kernel-PnP a configurat (400) un dispozitiv din clasa Net sau un radio Bluetooth pe un sistem air-gapped sau autonom.",
            ["400 apare la prima instalare și la schimbări de driver: nu dovedește un adaptor nou fizic.", "Adaptoarele virtuale (listă de date) sunt tratate cu severitate mai mică.", "Activarea sau dezactivarea adaptorului nu este înregistrată separat în sursele colectate."],
            ["Starea actuală a adaptorului, istoricul de driver, setările BIOS."],
            ["Verificați adaptorul în Device Manager și BIOS.", "Comparați cu configurația hardware aprobată."]),
        R("SEQ-CONTROL-GAP-MEDIA", Seq, SemanticType.Correlation, "Un decalaj de control (USB, instalare de dispozitive, audit, Defender) este urmat, în interiorul decalajului sau în fereastra de după el, de un mediu amovibil observat.",
            ["Ordinea este cea din timp; nu dovedește o legătură între dezactivarea controlului și folosirea mediului și nu spune cine a modificat controlul.", "Constatarea de decalaj nu poartă momentul restabilirii: pasul „control restabilit” este întotdeauna neobservat, iar sfârșitul ferestrei este ultima înregistrare colectată.",
             "Prezența mediului nu este copiere; scrierile pe volum vin din MEDIA-FILE-ACTIVITY și nu arată conținutul."],
            ["Momentul și autorul modificării controlului (Security 4719/4657, GroupPolicy/Operational), restabilirea controlului, activitatea pe volumul mediului."],
            ["Verificați gpresult și starea efectivă a controlului.", "Examinați constatările componente (POLICY-CONTROL-GAP, MEDIA-*)."]),
        R("SEQ-SMB-STAGING-USB", Seq, SemanticType.Correlation, "Acces la o partajare de la distanță, urme de fișiere create local și scrieri pe un mediu amovibil, în această ordine și în ferestrele din date.",
            ["Fără legătură de nume de fișier, secvența este doar o corelare temporală; un nume egal nu dovedește același conținut (fără hash).", "Pasul de staging cere căi cu literă de unitate (un rând USN fără literă nu se deosebește de volumul mediului).",
             "Nu arată conținutul transferat și nu stabilește scopul; sursele care nu au fost colectate dau „pas neobservat”, nu absență."],
            ["Hash-urile fișierelor, 4663 cu SACL pe fișierele sensibile, jurnalul USN al volumului mediului, jurnalele serverului de fișiere."],
            ["Examinați constatările componente (SMB, MEDIA-FILE-ACTIVITY).", "Comparați fișierele de pe mediu cu cele accesate pe partajare, după hash, dacă mediul este disponibil."]),
        R("SEQ-PORTABLE-USB-ARCHIVE", Seq, SemanticType.Correlation, "Software portabil sau rulat de pe un mediu amovibil, apărut în perioadă, o arhivă creată și scrieri pe un mediu amovibil, în ferestrele din date.",
            ["Prima apariție este prima din artefactele colectate, nu dovada că programul nu exista înainte; Amcache arată prezență, nu execuție.", "Dimensiunea arhivei se știe doar când o sursă o conține; fără ea arhiva se raportează cu dimensiune necunoscută.",
             "Legătura program → arhivă → mediu este temporală; numele de fișier egale nu dovedesc același conținut."],
            ["Hash-urile arhivei și ale fișierelor de pe mediu, jurnalele programului, contul care a pornit programul (Prefetch nu îl conține)."],
            ["Examinați constatările componente (MEDIA-*, REMOTE-TOOL-*).", "Verificați arhiva și conținutul ei dacă mai există."]),
    ];

    private static readonly Dictionary<string, RuleContract> ById = All.ToDictionary(r => r.RuleId, StringComparer.Ordinal);

    public static RuleContract? For(string ruleId) => ById.GetValueOrDefault(ruleId);
}
