<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <PackageReference Include="MediatR" />
    <PackageReference Include="FluentValidation" />
    <PackageReference Include="FluentValidation.DependencyInjectionExtensions" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Balsam.Inventory.Domain\Balsam.Inventory.Domain.csproj" />
    <ProjectReference Include="..\..\..\Balsam.SharedKernel\Balsam.SharedKernel.csproj" />
  </ItemGroup>

</Project>
