<Project Sdk="Microsoft.NET.Sdk.Worker">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Aspire.Microsoft.EntityFrameworkCore.SqlServer" Version="13.5.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\VolumeMount.Data\VolumeMount.Data.csproj" />
    <ProjectReference Include="..\VolumeMount.ServiceDefaults\VolumeMount.ServiceDefaults.csproj" />
  </ItemGroup>

</Project>
