<Project Sdk="Microsoft.NET.Sdk.Web">

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" />
    <PackageReference Include="Serilog.AspNetCore" />
    <PackageReference Include="Serilog.Sinks.Console" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Balsam.SharedKernel\Balsam.SharedKernel.csproj" />
    <ProjectReference Include="..\Balsam.Infrastructure\Balsam.Infrastructure.csproj" />
    <ProjectReference Include="..\Modules\Identity\Balsam.Identity.Api\Balsam.Identity.Api.csproj" />
    <ProjectReference Include="..\Modules\Identity\Balsam.Identity.Infrastructure\Balsam.Identity.Infrastructure.csproj" />
    <ProjectReference Include="..\Modules\Entity\Balsam.Entity.Api\Balsam.Entity.Api.csproj" />
    <ProjectReference Include="..\Modules\Entity\Balsam.Entity.Infrastructure\Balsam.Entity.Infrastructure.csproj" />
    <ProjectReference Include="..\Modules\Inventory\Balsam.Inventory.Api\Balsam.Inventory.Api.csproj" />
    <ProjectReference Include="..\Modules\Inventory\Balsam.Inventory.Infrastructure\Balsam.Inventory.Infrastructure.csproj" />
    <ProjectReference Include="..\Modules\POS\Balsam.POS.Api\Balsam.POS.Api.csproj" />
    <ProjectReference Include="..\Modules\POS\Balsam.POS.Infrastructure\Balsam.POS.Infrastructure.csproj" />
    <ProjectReference Include="..\Modules\Customer\Balsam.Customer.Api\Balsam.Customer.Api.csproj" />
    <ProjectReference Include="..\Modules\Customer\Balsam.Customer.Infrastructure\Balsam.Customer.Infrastructure.csproj" />
    <ProjectReference Include="..\Modules\Prescription\Balsam.Prescription.Api\Balsam.Prescription.Api.csproj" />
    <ProjectReference Include="..\Modules\Prescription\Balsam.Prescription.Infrastructure\Balsam.Prescription.Infrastructure.csproj" />
  </ItemGroup>

</Project>
