"""30_SCRIPTS/knowledge/audit_edge_purge.py — Independent Audit Edge Purge.

Executes the pruning of edges rejected during independent audit (e.g. edge_audit_v2).
Guarantees:
1. Sample SHA-256 verification before any action.
2. Transactional pruning strictly through graph.plasticity.PlasticityEngine.
3. Separation of dry-run and apply modes.
4. Detailed before/after edge metrics generated by script.
"""
from __future__ import annotations

import argparse
import hashlib
import json
import os
import sys
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Dict, List, Set, Tuple

REPO = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(REPO / "03_IMPLEMENTATION" / "packages"))
os.environ.setdefault("MEMORY_CONTROLLER_HMAC_SECRET", "0" * 40)

from graph.plasticity import PlasticityEngine, PruneResult
from graph.synapse_store import SynapseStore
from retrieval.vault_index import VaultIndex

DEFAULT_SAMPLE = REPO / "07_EVALUATION" / "edge_audit_v2" / "audit_sample_declared_50.json"
DEFAULT_VERDICTS = REPO / "07_EVALUATION" / "edge_audit_v2" / "audit_verdicts_declared.json"
DEFAULT_DRY_REPORT = REPO / "07_EVALUATION" / "edge_audit_v2" / "audit_purge_dry_run_report.md"


def verify_sample_hash(sample_path: Path, verdicts_path: Path) -> Tuple[bool, str, str]:
    """Verifies that sample file content hash matches sample_sha256 in verdicts."""
    raw = sample_path.read_bytes()
    normalized = raw.replace(b"\r\n", b"\n")
    digest = hashlib.sha256(normalized).hexdigest()

    verdicts_data = json.loads(verdicts_path.read_text(encoding="utf-8"))
    expected = verdicts_data.get("sample_sha256", "")
    return (digest == expected, digest, expected)


def load_rejected_edges(sample_path: Path, verdicts_path: Path) -> List[Dict[str, Any]]:
    """Extracts all edges marked REJECT in verdicts, matched by index."""
    verdicts_data = json.loads(verdicts_path.read_text(encoding="utf-8"))
    verdicts_list = verdicts_data.get("verdicts", [])
    reject_by_index = {v["index"]: v for v in verdicts_list if v.get("verdict") == "REJECT"}

    sample_data = json.loads(sample_path.read_text(encoding="utf-8"))
    samples_list = sample_data.get("samples", [])

    rejected_edges = []
    for s in samples_list:
        idx = s.get("index")
        if idx in reject_by_index:
            v_info = reject_by_index[idx]
            item = dict(s)
            item["rejection_category"] = v_info.get("category")
            item["rejection_rationale"] = v_info.get("rationale")
            rejected_edges.append(item)

    return rejected_edges


def generate_dry_run_report(
    rejected_edges: List[Dict[str, Any]],
    store: SynapseStore,
    sample_sha: str,
    output_path: Path,
) -> str:
    """Generates a structured markdown report detailing all edges that would be pruned."""
    by_category: Dict[str, List[Dict[str, Any]]] = {}
    by_relation: Dict[str, int] = {}
    for edge in rejected_edges:
        cat = edge.get("rejection_category") or "unspecified"
        by_category.setdefault(cat, []).append(edge)
        rel = edge.get("relation", "unknown")
        by_relation[rel] = by_relation.get(rel, 0) + 1

    total_edges_before = len(store.all())
    typed_before = sum(1 for e in store.all() if e.relation != "related_to")

    lines = [
        "# Raport Dry-Run: Curățarea celor 29 de Muchii Respinse la Audit",
        "",
        f"- **Dată generare**: {datetime.now(timezone.utc).isoformat(timespec='seconds')}",
        f"- **Eșantion auditat**: `07_EVALUATION/edge_audit_v2/audit_sample_declared_50.json`",
        f"- **SHA-256 Eșantion (verificat)**: `{sample_sha}`",
        f"- **Muchii propuse spre ștergere**: {len(rejected_edges)}",
        f"- **Mod de execuție**: DRY-RUN (nicio modificare aplicată asupra depozitului sau grafului)",
        "",
        "---",
        "",
        "## 1. Măsurători de Graf (Înainte vs. După Simulare)",
        "",
        "| Metrică | Înainte de Purjare | După Purjare (Simulat) | Delta |",
        "|---|---:|---:|---:|",
        f"| Total muchii graf | {total_edges_before} | {total_edges_before - len(rejected_edges)} | -{len(rejected_edges)} |",
        f"| Muchii tipizate (`relation != related_to`) | {typed_before} | {typed_before - len(rejected_edges)} | -{len(rejected_edges)} |",
        "",
        "---",
        "",
        "## 2. Distribuție pe Tipuri de Relații",
        "",
        "| Relație | Număr Muchii Respinse |",
        "|---|---:|",
    ]
    for rel, count in sorted(by_relation.items(), key=lambda x: -x[1]):
        lines.append(f"| `{rel}` | {count} |")

    lines.extend([
        "",
        "---",
        "",
        "## 3. Distribuție pe Motive de Respingere",
        "",
        "| Categorie Respingere | Număr Muchii |",
        "|---|---:|",
    ])
    for cat, items in sorted(by_category.items(), key=lambda x: -len(x[1])):
        lines.append(f"| `{cat}` | {len(items)} |")

    lines.extend([
        "",
        "---",
        "",
        "## 4. Tabelul Detaliat al celor 29 de Muchii de Șters",
        "",
        "| Index | Relație | Sursă | Țintă | Motiv Respingere | Rationale |",
        "|---:|---|---|---|---|---|",
    ])

    for edge in sorted(rejected_edges, key=lambda x: x["index"]):
        idx = edge["index"]
        rel = edge["relation"]
        src_title = edge.get("source_title", edge.get("source_id", ""))
        tgt_title = edge.get("target_title", edge.get("target_id", ""))
        src_path = edge.get("source_path", "")
        cat = edge.get("rejection_category", "")
        rat = (edge.get("rejection_rationale", "") or "").replace("\n", " ")
        lines.append(
            f"| {idx} | `{rel}` | [{src_title}]({src_path}) | {tgt_title} | `{cat}` | {rat} |"
        )

    lines.extend([
        "",
        "---",
        "",
        "## 5. Concluzie & Plan de Aplicare",
        "",
        "Toate cele 29 de muchii identificate sunt prezente în `SynapseStore` și corespund",
        "declarațiilor de relații din frontmatter-ul notelor-sursă.",
        "Ștergerea se va efectua tranzacțional prin `graph.plasticity.PlasticityEngine` cu",
        "garanție completă de rollback byte-cu-byte.",
    ])

    content = "\n".join(lines) + "\n"
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(content, encoding="utf-8")
    return content


def main() -> int:
    parser = argparse.ArgumentParser(description="Prune audited rejected edges from synapse store")
    parser.add_argument("--sample", type=Path, default=DEFAULT_SAMPLE)
    parser.add_argument("--verdicts", type=Path, default=DEFAULT_VERDICTS)
    parser.add_argument("--dry-run", action="store_true", help="Simulate pruning without mutating store")
    parser.add_argument("--report-out", type=Path, default=DEFAULT_DRY_REPORT)
    parser.add_argument("--run-id", type=str, default=None)
    args = parser.parse_args()

    sys.stdout.reconfigure(encoding="utf-8", errors="replace")

    print("Verifying sample hash against verdicts...")
    is_valid, calc_hash, exp_hash = verify_sample_hash(args.sample, args.verdicts)
    if not is_valid:
        print(f"FATAL: Sample hash mismatch!\nCalculated: {calc_hash}\nExpected:   {exp_hash}")
        return 1
    print(f"Sample SHA-256 verified OK: {calc_hash}")

    rejected_edges = load_rejected_edges(args.sample, args.verdicts)
    print(f"Loaded {len(rejected_edges)} rejected edges from verdicts (expected: 29).")
    if len(rejected_edges) != 29:
        print(f"WARNING: Expected exactly 29 rejections, got {len(rejected_edges)}")

    index = VaultIndex.load(str(REPO), include_raw=True, include_archived=True)
    store = SynapseStore.from_index(index)
    total_before = len(store.all())
    print(f"Initial store edges: {total_before}")

    engine = PlasticityEngine()
    edges_to_prune = [(r["source_id"], r["target_id"], r["relation"]) for r in rejected_edges]

    if args.dry_run:
        print("Running DRY-RUN simulation...")
        res = engine.prune_edges(store, edges_to_prune, dry_run=True, reason="audit_rejection")
        print(f"Dry-run simulation complete: {res.edges_pruned} edges would be pruned.")
        print(f"Store count remains untouched: {len(store.all())}")
        report_content = generate_dry_run_report(rejected_edges, store, calc_hash, args.report_out)
        print(f"Dry-run report written to: {args.report_out}")
        return 0
    else:
        run_id = args.run_id or f"audit_purge_{datetime.now(timezone.utc).strftime('%Y%m%dT%H%M%SZ')}"
        print(f"Executing REAL prune with run_id: {run_id}...")
        res = engine.prune_edges(store, edges_to_prune, run_id=run_id, dry_run=False, reason="audit_rejection")
        print(f"Real prune complete: {res.edges_pruned} edges pruned.")
        print(f"Store count after prune: {len(store.all())} (delta: {len(store.all()) - total_before})")
        return 0


if __name__ == "__main__":
    sys.exit(main())
