"""plasticity_update.py — Plasticity Prototype (owner: claude-code).

Status: EXPERIMENTAL — NOT RUNTIME INTEGRATED. This is the only path by which
the derived synapse graph rewrites itself. The rule, plainly:

    A synapse strengthens ONLY if it was in the OBSERVED trace of a run whose
    outcome was verified by an external authority (pytest, CI, an outcome
    ledger, or explicit human verification) — NEVER because the model said it
    was useful.

Design constraint from the runtime/security owner (Codex): this module must
NOT modify memory_controller/memory_trace.py or
memory_controller/outcome_tracker.py — those are owned by Codex. This file is
an ADAPTER: it only ever reads whatever those modules (or, absent them in a
given environment, a plain JSON outcome ledger) already produced, and writes
exclusively to the derived, regenerable cognitive_core/synapse_store.py
artifact (05_DATA/synapses.json). It never touches memory_controller/**.

    verified outcome + observed trace -> weight update
    (missing either one)              -> NO UPDATE

    python 30_SCRIPTS/knowledge/plasticity_update.py --run-id r123 --success
    python 30_SCRIPTS/knowledge/plasticity_update.py --from-ledger --consolidate
"""
from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path
from typing import List, Optional, Tuple

sys.path.insert(0, str(Path(__file__).resolve().parents[2]))
sys.path.insert(0, str(Path(__file__).resolve().parents[2] / "03_IMPLEMENTATION" / "packages"))
from cognitive_core.synapse_store import SynapseStore  # noqa: E402
from cognitive_core.plasticity import (  # noqa: E402
    AttributionModel,
    PlasticityEngine,
    PlasticityJournal,
    MemoryAttributionState,
)

# Sources acceptable as "externally verified". Explicitly excludes any form of
# model self-report ("memory was helpful", sentiment, implicit usage).
VERIFIED_SOURCES = {"pytest", "ci", "outcome_ledger", "human_verified", "manual_verified"}


def _ensure_utf8_stdout() -> None:
    """See 30_SCRIPTS/knowledge/edge_proposer.py::_ensure_utf8_stdout.
    Empirically confirmed to be BLOCKING for this script specifically: on
    stock Windows console encoding, the crash occurred inside the success
    print branch, i.e. exactly on the path that matters, BEFORE
    store.save() — meaning no successful reinforcement was ever persisted."""
    for stream in (sys.stdout, sys.stderr):
        try:
            stream.reconfigure(encoding="utf-8", errors="replace")
        except (AttributeError, ValueError):
            pass


def load_trace(trace_dir: Path, pack_id: str) -> Optional[dict]:
    """Reads a brain_pack.py OBSERVED trace (cognitive_core/brain_pack.py ->
    BrainPack.observed_trace()), generated by code BEFORE the model consumed
    the pack. Never accepts a trace synthesized after the fact from a model's
    own account of what it used."""
    path = trace_dir / f"{pack_id}.json"
    if not path.exists():
        return None
    try:
        return json.loads(path.read_text(encoding="utf-8"))
    except json.JSONDecodeError:
        return None


def outcomes_from_ledger(ledger: Path) -> List[Tuple[str, bool, str]]:
    """(pack_id, success, source) from an existing outcome ledger. This reads
    whatever artifact memory_controller/outcome_tracker.py (or an equivalent
    plain JSON/JSONL ledger) already produced — it never writes to it, and
    this module does not assume that file's schema is owned by claude-code."""
    if not ledger.exists():
        return []
    records = []
    text = ledger.read_text(encoding="utf-8")
    try:
        data = json.loads(text)
        rows = data if isinstance(data, list) else data.get("records", [])
    except json.JSONDecodeError:
        rows = []
        for line in text.splitlines():
            if not line.strip():
                continue
            try:
                rows.append(json.loads(line))
            except json.JSONDecodeError:
                continue
    for r in rows:
        if not isinstance(r, dict):
            continue
        pack_id = r.get("pack_id") or r.get("context_pack_id")
        source = str(r.get("verification_source") or r.get("source") or "")
        if not pack_id or source.lower() not in VERIFIED_SOURCES:
            continue  # no external verification => no effect on weights, period
        success = bool(r.get("success", r.get("outcome") == "success"))
        records.append((pack_id, success, source))
    return records


def main() -> int:
    _ensure_utf8_stdout()
    ap = argparse.ArgumentParser()
    ap.add_argument("--vault", default=".")
    ap.add_argument("--synapses", default="05_DATA/synapses.json")
    ap.add_argument("--trace-dir", default="08_OBSERVABILITY/brain_pack_traces")
    ap.add_argument("--ledger", default="05_DATA/outcome_ledger.json")
    ap.add_argument("--pack-id")
    ap.add_argument("--success", action="store_true")
    ap.add_argument("--failure", action="store_true")
    ap.add_argument("--from-ledger", action="store_true")
    ap.add_argument("--journal", default="telemetry/plasticity_journal.jsonl",
                    help="Path to append-only telemetry journal")
    ap.add_argument("--rollback", metavar="RUN_ID",
                    help="Roll back weight updates for the specified run ID")
    ap.add_argument("--used-ids", default="",
                    help="Comma-separated IDs of memories actually used in the run")
    ap.add_argument("--consolidate", action="store_true",
                    help="Runs atrophy + pruning of unreinforced edges")
    ap.add_argument("--rate", type=float, default=0.15)
    args = ap.parse_args()

    vault = Path(args.vault)
    store = SynapseStore.load(vault / args.synapses)
    if not store.all():
        print("No SynapseStore. Run edge_proposer.py first (or promote declared relations).")
        return 1
    if store.rejected_on_load():
        print(f"  [warn] {len(store.rejected_on_load())} malformed synapse record(s) "
              f"skipped on load")

    journal = PlasticityJournal(vault / args.journal)

    if args.rollback:
        rb_res = journal.rollback(args.rollback, store)
        store.save(vault / args.synapses)
        print(f"rollback: {rb_res.edges_reverted} edge(s) restored for {args.rollback}")
        return 0

    trace_dir = vault / args.trace_dir
    updates: List[Tuple[str, bool, str]] = []
    if args.from_ledger:
        updates = outcomes_from_ledger(vault / args.ledger)
    if args.pack_id:
        if not (args.success ^ args.failure):
            print("Specify exactly one of: --success or --failure")
            return 2
        updates.append((args.pack_id, args.success, "manual_verified"))

    if not updates:
        print("No externally verified outcome to apply. Weights unchanged.")
    applied = 0
    explicit_used_ids = [u.strip() for u in args.used_ids.split(",") if u.strip()]
    engine = PlasticityEngine(journal=journal, default_rate=args.rate)

    for pack_id, success, source in updates:
        trace = load_trace(trace_dir, pack_id)
        if trace is None:
            print(f"  [skip] {pack_id}: no observed trace -> NO UPDATE")
            continue

        used_ids = explicit_used_ids or trace.get("used_memory_ids", [])
        outcome_rec = {
            "run_id": pack_id,
            "outcome": "success" if success else "fail",
            "verification_method": source,
        }

        if "graph_edges_traversed" in trace or "final_context_ids" in trace or used_ids:
            res = engine.apply_outcome(
                synapse_store=store,
                candidate_trace=trace,
                outcome_record=outcome_rec,
                used_memory_ids=used_ids,
                run_id=pack_id,
                rate=args.rate,
            )
            applied += res.applied_count
            mark = "OK" if success else "FAIL"
            print(f"  {pack_id} [{source}] {mark}: {res.applied_count} synapse(s) adjusted (status: {res.status})")
        else:
            edges = [tuple(e) for e in trace.get("observed_edges", [])]
            touched = store.reinforce(edges, run_id=pack_id, success=success, rate=args.rate)
            applied += touched
            mark = "OK" if success else "FAIL"
            print(f"  {pack_id} [{source}] {mark}: {touched} synapse(s) adjusted "
                  f"out of {len(edges)} observed")

    if args.consolidate:
        store.decay_unused()
        removed = store.prune()
        print(f"  consolidation: {removed} atrophied synapse(s) pruned")

    store.save(vault / args.synapses)
    print(f"state: {store.degree_stats()} :: {applied} adjustment(s) -> {args.synapses}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
