import { createVoiceEngine, speak } from './voice_engine.js';

const API='http://127.0.0.1:8000/api/v1';
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const timeline=[]; let agents=[]; let skills=[]; let chatHistory=[]; let voice=null;

const immersive=document.createElement('link'); immersive.rel='stylesheet'; immersive.href='/css/jarvis-immersive.css'; document.head.appendChild(immersive);
function esc(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));}
function stamp(){return new Date().toLocaleTimeString('ro-RO',{hour12:false});}
function logEvent(type,message,detail=''){timeline.unshift({time:stamp(),type,message,detail});timeline.splice(25);const el=$('#timeline');if(el)el.innerHTML=timeline.slice(0,10).map(e=>`<div><b>${esc(e.time)}</b><span>${esc(e.message)}${e.detail?` · ${esc(e.detail)}`:''}</span><em class="${esc(e.type)}">${e.type==='error'?'FAILED':e.type==='write'?'QUEUED':e.type==='route'?'ROUTED':'COMPLETED'}</em></div>`).join('')||'<div class="muted">No activity yet.</div>';}
async function request(path,options={}){const r=await fetch(`${API}${path}`,options);if(!r.ok){const text=await r.text().catch(()=> '');throw new Error(text||`HTTP ${r.status}`)}return r.json();}
function setOnline(online){const p=$('#vault-state');p.classList.toggle('online',online);p.classList.toggle('offline',!online);p.innerHTML=`<i></i> ${online?'ONLINE':'OFFLINE'}`;$('#s-memory').textContent=online?'ONLINE':'OFFLINE';$('#orb-label')?.textContent=online?'LINK':'WAIT';$('#core-state').textContent=online?'VAULT LINK ESTABLISHED':'WAITING FOR VAULT LINK';$('#mind-state').textContent=online?'AWAKE':'OFFLINE';}
async function refreshStatus(){const t=performance.now();try{const [status,metrics,models]=await Promise.all([request('/status'),request('/metrics'),request('/models')]);setOnline(true);$('#metric-notes').textContent=Number(metrics.memory_items??status.indexed_notes??0).toLocaleString('en-US');$('#metric-agents').textContent=`${metrics.agents_online??0}/${metrics.agents_total??0}`;$('#metric-skills').textContent=Number(metrics.skills_operational??0).toLocaleString('en-US');$('#metric-proposals').textContent=metrics.proposals_pending??0;$('#proposal-state-count').textContent=metrics.proposals_pending??0;$('#side-notes').textContent=metrics.memory_items??0;$('#side-agents').textContent=metrics.agents_online??0;$('#side-skills').textContent=metrics.skills_operational??0;$('#side-pending').textContent=metrics.proposals_pending??0;$('#footer-agents').textContent=metrics.agents_total??0;$('#footer-skills').textContent=metrics.skills_operational??0;$('#router-state').textContent='READY';$('#model-label').textContent=`LOCAL MODEL ${models.default||'OFFLINE'}`;$('#model-short').textContent=models.default||'OFFLINE';$('#s-llm').textContent=models.available?'ONLINE':'OFFLINE';$('#latency').textContent=`API ${Math.round(performance.now()-t)}ms`;const select=$('#chat-model');if(select&&select.options.length===1){(models.models||[]).forEach(m=>select.add(new Option(m,m)));}}catch(e){setOnline(false);$('#router-state').textContent='OFFLINE';$('#s-llm').textContent='OFFLINE';$('#model-short').textContent='OFFLINE';$('#latency').textContent='API —';logEvent('error','Vault API unavailable',e.message);}$('#clock').textContent=stamp();$('#last-refresh').textContent=stamp();}
function renderResults(data){const box=$('#search-results'),rows=data.results||[];if(!rows.length){box.className='results empty';box.textContent='No relevant memory found.';return;}box.className='results';box.innerHTML=rows.map(x=>`<article class="result-card"><strong>${esc(x.title||x.name||x.id||'Untitled memory')}</strong><small>${esc(x.id||'canonical-memory')}</small><div>${esc(String(x.content||x.text||x.preview||'').slice(0,420))}</div></article>`).join('');}
async function searchMemory(q,recent=false){if(!q&&!recent)return;const box=$('#search-results');if(!recent){box.className='results empty';box.textContent='Retrieving relevant memory…';logEvent('route','Memory retrieval started',q);}try{const d=await request(`/search?q=${encodeURIComponent(q)}`);if(recent){const rb=$('#recent-memory'),rows=(d.results||[]).slice(0,5);rb.innerHTML=rows.map((x,i)=>`<article><i>${String(i+1).padStart(2,'0')}</i><div><b>${esc(x.title||x.name||x.id||'Memory')}</b><span>${esc(x.updated||x.created||'Canonical memory')}</span></div></article>`).join('')||'<div class="muted">No indexed memory.</div>';}else{renderResults(d);logEvent('ok','Memory retrieval completed',`${d.total_results??0} results`);}}catch(e){if(recent)$('#recent-memory').innerHTML='<div class="muted">Recent memory unavailable.</div>';else{box.className='results empty';box.textContent=`Memory retrieval unavailable: ${e.message}`;logEvent('error','Memory retrieval failed',e.message);}}}
function renderAgents(){const g=$('#agent-grid');g.innerHTML=agents.map((a,i)=>`<article class="agent-card" data-agent="${esc(a.id)}"><div class="agent-top"><span class="agent-icon">${String(i+1).padStart(2,'0')}</span><div><strong>${esc(a.name)}</strong><small>${esc(a.domain)}</small></div></div><div class="skill-chips">${(a.skills||[]).slice(0,6).map(s=>`<span>${esc(s)}</span>`).join('')}</div><button class="agent-btn" type="button">ASSIGN AGENT</button></article>`).join('');$$('.agent-btn').forEach(b=>b.addEventListener('click',e=>{e.stopPropagation();selectAgent(b.closest('.agent-card').dataset.agent);}));$$('.agent-card').forEach(c=>c.addEventListener('click',()=>selectAgent(c.dataset.agent)));$('#council-count').textContent=`${agents.length} AGENTS`;}
function selectAgent(id){const a=agents.find(x=>x.id===id);if(!a)return;$$('.agent-card').forEach(c=>c.classList.toggle('selected',c.dataset.agent===id));$('#route-input').value=a.domain;$('#search-input').value=a.name;$('#chat-agent').textContent=`ROUTER: ${a.name}`;logEvent('route','Agent selected',`${a.name} · ${a.domain}`);}
async function loadAgents(){try{const d=await request('/agents');agents=d.agents||[];renderAgents();logEvent('ok','Agent Council loaded',`${agents.length} agents`);}catch(e){$('#agent-grid').innerHTML=`<div class="loading">Agent registry unavailable: ${esc(e.message)}</div>`;logEvent('error','Agent registry unavailable',e.message);}}
async function routeTask(task){if(!task)return;const box=$('#route-results');box.className='route-results empty';box.textContent='Ranking agents and capabilities…';logEvent('route','Agent routing started',task);try{const d=await request('/route',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({task})});const rows=d.selected||[];box.className='route-results';box.innerHTML=rows.map((a,i)=>`<article class="route-card ${i===0?'selected':''}" data-id="${esc(a.id)}"><strong>${esc(a.name)}</strong><small>${esc(a.domain)}</small><div class="skill-chips">${(a.skills||[]).slice(0,4).map(s=>`<span>${esc(s)}</span>`).join('')}</div><div class="route-score">SCORE ${a.route_score}${a.matched_terms?.length?` · ${esc(a.matched_terms.join(', '))}`:''}</div></article>`).join('')||'<div class="route-results empty">No compatible agent found.</div>';$$('.route-card').forEach(c=>c.addEventListener('click',()=>{selectAgent(c.dataset.id);$$('.route-card').forEach(x=>x.classList.remove('selected'));c.classList.add('selected');}));logEvent('route','Agent routing completed',`${rows.length} candidates`);}catch(e){box.className='route-results empty';box.textContent=`Routing unavailable: ${e.message}`;logEvent('error','Agent routing failed',e.message);}}
async function loadSkills(q=''){try{const d=await request(`/skills${q?`?q=${encodeURIComponent(q)}`:''}`);skills=d.skills||[];$('#skill-total').textContent=d.total??skills.length;$('#skill-cloud').innerHTML=skills.slice(0,120).map(s=>`<span title="${esc(s.path)}">${esc(s.name||s.id)}</span>`).join('')||'<span>No skills found.</span>';logEvent('ok','Skill registry loaded',`${skills.length} returned`);}catch(e){$('#skill-cloud').innerHTML='<span>Skill registry unavailable.</span>';logEvent('error','Skill registry unavailable',e.message);}}
function renderProposals(d){const pending=d.pending||[];$('#proposal-state-count').textContent=pending.length;$('#metric-proposals').textContent=pending.length;$('#side-pending').textContent=pending.length;$('#pending-proposals').innerHTML=pending.slice(0,5).map(p=>`<div class="proposal" data-candidate="${esc(p.candidate_id)}"><div><b>${esc(String(p.content||p.type||'Proposal').slice(0,52))}</b><small>${esc(p.type||'fact')}</small></div><div class="proposal-actions"><button class="tiny-btn proposal-decision" data-decision="APPROVED">APPROVE</button><button class="tiny-btn proposal-decision danger-btn" data-decision="REJECTED">REJECT</button></div></div>`).join('')||'<div class="muted">Queue clear.</div>';$$('.proposal-decision').forEach(b=>b.addEventListener('click',()=>decideProposal(b.closest('.proposal').dataset.candidate,b.dataset.decision)));}
async function loadProposals(){try{renderProposals(await request('/proposals'));}catch(e){$('#pending-proposals').innerHTML='<div class="muted">Proposal queue unavailable.</div>';}}
async function decideProposal(id,decision){try{await request(`/proposals/${encodeURIComponent(id)}/decision`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({decision})});logEvent(decision==='APPROVED'?'write':'error',`Proposal ${decision.toLowerCase()}`,id);await loadProposals();await refreshStatus();}catch(e){logEvent('error','Proposal decision failed',e.message);}}
function addChat(role,text,meta=''){const log=$('#chat-log');const node=document.createElement('div');node.className=`chat-message ${role}`;node.innerHTML=`<div class="avatar">${role==='assistant'?'J':'U'}</div><div><strong>${role==='assistant'?'JARVIS':'YOU'}</strong><p>${esc(text).replace(/\n/g,'<br>')}</p>${meta?`<small>${esc(meta)}</small>`:''}</div>`;log.appendChild(node);log.scrollTop=log.scrollHeight;}
async function sendChat(message){const status=$('#chat-status');status.textContent='THINKING';$('#mind-state').textContent='THINKING';addChat('user',message);$('#chat-input').value='';try{const chosen=$('#chat-model').value;const d=await request('/chat',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({message,model:chosen,history:chatHistory})});chatHistory.push({role:'user',content:message},{role:'assistant',content:d.reply});chatHistory=chatHistory.slice(-12);addChat('assistant',d.reply,`${d.model} · ${d.agent} · ${d.memory_hits} memory hits`);$('#chat-status').textContent='READY';$('#chat-agent').textContent=`ROUTER: ${d.agent}`;$('#mind-state').textContent='AWAKE';logEvent('ok','JARVIS response completed',`${d.model} · ${d.agent}`);if($('#voice-toggle').dataset.enabled==='true')speak(d.reply);}catch(e){status.textContent='OFFLINE';$('#mind-state').textContent='ERROR';addChat('assistant',`I could not reach the local model. ${e.message}`,'Check Ollama / JARVIS_MODEL');logEvent('error','JARVIS chat failed',e.message);}}
async function submitProposal(e){e.preventDefault();const content=$('#proposal-input').value.trim();if(!content)return;const f=$('#proposal-feedback');f.textContent='Submitting to Memory V6 queue…';try{const d=await request('/propose',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({type:$('#proposal-type').value,content})});f.textContent=`Queued: ${d.candidate_id}`;logEvent('write','Memory proposal queued',d.candidate_id);await loadProposals();await refreshStatus();setTimeout(()=>$('#proposal-dialog').close(),700);}catch(err){f.textContent=`Proposal failed: ${err.message}`;logEvent('error','Memory proposal failed',err.message);}}
function openProposal(){const d=$('#proposal-dialog');$('#proposal-feedback').textContent='Candidate enters Memory V6 PENDING_REVIEW.';$('#proposal-input').value='';d.showModal?.();}
async function diagnostics(){const start=performance.now();logEvent('route','Diagnostics started');try{const [s,m,a,k]=await Promise.all([request('/status'),request('/metrics'),request('/agents'),request('/skills')]);$('#latency').textContent=`DIAG ${Math.round(performance.now()-start)}ms`;logEvent('ok','Diagnostics passed',`${a.agents?.length||0} agents · ${k.total||0} skills`);}catch(e){$('#latency').textContent='DIAG FAILED';logEvent('error','Diagnostics failed',e.message);}}

$('#search-form').addEventListener('submit',e=>{e.preventDefault();searchMemory($('#search-input').value.trim())});$('#quick-go').addEventListener('click',()=>searchMemory($('#quick-search').value.trim()));$('#quick-search').addEventListener('keydown',e=>{if(e.key==='Enter')searchMemory(e.target.value.trim())});$('#focus-search').addEventListener('click',()=>{$('#search-input').focus();$('#memory-panel').scrollIntoView({behavior:'smooth',block:'center'})});$('#focus-chat').addEventListener('click',()=>{$('#chat-input').focus();$('#chat-panel').scrollIntoView({behavior:'smooth',block:'center'})});$('#new-proposal').addEventListener('click',openProposal);$('#proposal-form').addEventListener('submit',submitProposal);$('#diagnostics').addEventListener('click',diagnostics);$('#route-form').addEventListener('submit',e=>{e.preventDefault();routeTask($('#route-input').value.trim())});$('#skill-filter-btn').addEventListener('click',()=>loadSkills($('#skill-filter').value.trim()));$('#skill-filter').addEventListener('keydown',e=>{if(e.key==='Enter')loadSkills(e.target.value.trim())});$('#clear-timeline').addEventListener('click',()=>{timeline.length=0;logEvent('ok','Timeline cleared')});$('#chat-form').addEventListener('submit',e=>{e.preventDefault();const m=$('#chat-input').value.trim();if(m)sendChat(m)});$('#chat-input').addEventListener('keydown',e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();$('#chat-form').requestSubmit()}});$$('.chips button').forEach(b=>b.addEventListener('click',()=>{const q=b.dataset.query||'';$('#quick-search').value=q;searchMemory(q)}));$$('.tab').forEach(tab=>tab.addEventListener('click',()=>{$$('.tab').forEach(x=>x.classList.remove('active'));tab.classList.add('active');const targets={overview:'.core-grid',chat:'#chat-panel',memory:'#memory-panel',agents:'#agents-panel',skills:'#skills-panel',execution:'#execution-panel'};document.querySelector(targets[tab.dataset.view])?.scrollIntoView({behavior:'smooth',block:'center'})}));
voice=createVoiceEngine({onText:text=>{$('#chat-input').value=text;sendChat(text)},onState:state=>{$('#voice-toggle').textContent=state}});$('#voice-toggle').addEventListener('click',()=>{if(!voice){$('#voice-status')?.textContent='VOICE UNSUPPORTED';return;}$('#voice-toggle').dataset.enabled='true';voice.start()});
(async()=>{renderAgents();await Promise.all([loadAgents(),loadSkills(),loadProposals(),refreshStatus()]);await searchMemory('',true)})();
setInterval(refreshStatus,15000);setInterval(loadProposals,20000);setInterval(()=>$('#clock').textContent=stamp(),1000);
