const canvas=document.querySelector('#jarvis-3d');let gl=null,program=null,positionBuffer=null,colorBuffer=null,count=0,rotation=0,last=0;
function mat4Perspective(o,fovy,aspect,near,far){const f=1/Math.tan(fovy/2),nf=1/(near-far);o[0]=f/aspect;o[1]=0;o[2]=0;o[3]=0;o[4]=0;o[5]=f;o[6]=0;o[7]=0;o[8]=0;o[9]=0;o[10]=(far+near)*nf;o[11]=-1;o[12]=0;o[13]=0;o[14]=2*far*near*nf;o[15]=0;return o}
function mat4Model(o,a,s=1){const c=Math.cos(a),q=Math.sin(a);o.set([c*s,0,-q*s,0,0,s,0,0,q*s,0,c*s,0,0,-0.08,-2.65,1]);return o}
function add(pts,cols,x,y,z,i=1){pts.push(x,y,z);cols.push(.2*i,.9*i,1*i,.88)}
function build(){const p=[],c=[];const ell=(rx,ry,rz,y0,steps,rows)=>{for(let r=0;r<=rows;r++){const v=-Math.PI/2+r/rows*Math.PI,cv=Math.cos(v),sv=Math.sin(v);for(let j=0;j<steps;j++){const a=j/steps*Math.PI*2;add(p,c,Math.cos(a)*cv*rx,y0+sv*ry,Math.sin(a)*cv*rz,1.05+(Math.sin(a)*cv>.1?.22:0))}}};ell(.58,.78,.48,.73,88,24);ell(.34,.42,.3,-.04,54,12);
for(let i=0;i<120;i++){const a=Math.PI*i/119,x=-.95+1.9*i/119,y=-.52+.12*Math.sin(a*2),z=.04*Math.cos(a*2);add(p,c,x,y,z,.52);add(p,c,-x,y,z,.52)}
for(let i=0;i<54;i++){const a=i/54*Math.PI*2;add(p,c,-.22+.055*Math.cos(a),.86+.035*Math.sin(a),.45,.95);add(p,c,.22+.055*Math.cos(a),.86+.035*Math.sin(a),.45,.95)}
for(let i=0;i<48;i++){const a=i/48*Math.PI*2;add(p,c,.0+.18*Math.cos(a),.55+.055*Math.sin(a),.47,.75)}
for(let r=0;r<5;r++){const radius=.18+r*.072;for(let i=0;i<80;i++){const a=i/80*Math.PI*2;add(p,c,Math.cos(a)*radius,-.72,Math.sin(a)*radius,1.25-r*.16)}}
for(let i=0;i<160;i++){const a=i/160*Math.PI*2;add(p,c,Math.cos(a)*1.02,.02,Math.sin(a)*1.02,.42)}
return {p:new Float32Array(p),c:new Float32Array(c)}}
function shader(t,s){const x=gl.createShader(t);gl.shaderSource(x,s);gl.compileShader(x);if(!gl.getShaderParameter(x,gl.COMPILE_STATUS))throw Error(gl.getShaderInfoLog(x)||'shader');return x}
function init(){if(!canvas)return;gl=canvas.getContext('webgl',{alpha:true,antialias:true});if(!gl){canvas.parentElement.classList.add('no-webgl');return}const vs=shader(gl.VERTEX_SHADER,'attribute vec3 p;attribute vec4 c;uniform mat4 proj;uniform mat4 model;varying vec4 v;void main(){gl_Position=proj*model*vec4(p,1.0);gl_PointSize=2.35;v=c;}'),fs=shader(gl.FRAGMENT_SHADER,'precision mediump float;varying vec4 v;void main(){float d=distance(gl_PointCoord,vec2(.5));if(d>.5)discard;float a=(1.0-d*2.0)*v.a;gl_FragColor=vec4(v.rgb,a);}');program=gl.createProgram();gl.attachShader(program,vs);gl.attachShader(program,fs);gl.linkProgram(program);if(!gl.getProgramParameter(program,gl.LINK_STATUS))throw Error(gl.getProgramInfoLog(program)||'program');const m=build();count=m.p.length/3;positionBuffer=gl.createBuffer();gl.bindBuffer(gl.ARRAY_BUFFER,positionBuffer);gl.bufferData(gl.ARRAY_BUFFER,m.p,gl.STATIC_DRAW);colorBuffer=gl.createBuffer();gl.bindBuffer(gl.ARRAY_BUFFER,colorBuffer);gl.bufferData(gl.ARRAY_BUFFER,m.c,gl.STATIC_DRAW);resize();window.addEventListener('resize',resize,{passive:true});requestAnimationFrame(frame)}
function resize(){if(!gl||!canvas)return;const d=Math.min(devicePixelRatio||1,2),r=canvas.getBoundingClientRect();canvas.width=Math.max(1,r.width*d);canvas.height=Math.max(1,r.height*d);gl.viewport(0,0,canvas.width,canvas.height)}
function frame(t){if(!gl||!program)return;const dt=Math.min(.05,(t-last)/1000||.016);last=t;rotation+=dt*.32;gl.clearColor(0,0,0,0);gl.clear(gl.COLOR_BUFFER_BIT|gl.DEPTH_BUFFER_BIT);gl.enable(gl.BLEND);gl.blendFunc(gl.SRC_ALPHA,gl.ONE);gl.useProgram(program);gl.bindBuffer(gl.ARRAY_BUFFER,positionBuffer);const pl=gl.getAttribLocation(program,'p');gl.enableVertexAttribArray(pl);gl.vertexAttribPointer(pl,3,gl.FLOAT,false,0,0);gl.bindBuffer(gl.ARRAY_BUFFER,colorBuffer);const cl=gl.getAttribLocation(program,'c');gl.enableVertexAttribArray(cl);gl.vertexAttribPointer(cl,4,gl.FLOAT,false,0,0);const aspect=canvas.width/Math.max(1,canvas.height),proj=new Float32Array(16),model=new Float32Array(16);mat4Perspective(proj,Math.PI/3,aspect,.1,10);mat4Model(model,rotation,1.04);gl.uniformMatrix4fv(gl.getUniformLocation(program,'proj'),false,proj);gl.uniformMatrix4fv(gl.getUniformLocation(program,'model'),false,model);gl.drawArrays(gl.POINTS,0,count);requestAnimationFrame(frame)}
init();
